### ISSUE TITLE
docker_container : declaring less published_ports does not recreate container

### ISSUE THREAD

**Issue by arnaud-quiblier** [ansible-collections/community.docker#1008]
Same as [ansible #24892](https://github.com/ansible/ansible/issues/24892), which should have been fixed long time ago :(

##### SUMMARY
Module does not recreate container when giving it less of `published_ports` than the container already has.
**Note :** the container is correctly recreated when some `published_ports` are added.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`community.docker.docker_container`

##### ANSIBLE VERSION

```
ansible [core 2.17.1]
  ansible python module location = ~/.virtualenvs/ansible-10.1/lib/python3.10/site-packages/ansible
  executable location = ~/.virtualenvs/ansible-10.1/bin/ansible
  python version = 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0] (~/.virtualenvs/ansible-10.1/bin/python)
```

##### OS / ENVIRONMENT
Host : Ubuntu 22.04 LTS / Debian 11
Managed : Debian 11

##### STEPS TO REPRODUCE
First you run :
```yaml
- name: Run container
  community.docker.docker_container:
    state: started
    image: "{{ my_image }}"
    name: "foo"
    published_ports:
      - "443:443"
      - "22:22"
```
Then you run :
```yaml
- name: Run container
  community.docker.docker_container:
    state: started
    image: "{{ my_image }}"
    name: "foo"
    published_ports:
      - "443:443"
```

##### EXPECTED RESULTS
I expected for the second run :
```
TASK [my-role : Run container] ***************************************************
changed: [my-host]
```
Plus of course, docker container to be recreated.

##### ACTUAL RESULTS
```
TASK [my-role : Run container] ***************************************************
ok: [my-host]
```
No change detected, container not recreated.
