### ISSUE TITLE
Docker copy in stopped mode

### ISSUE THREAD

**Issue by halradaideh** [ansible-collections/community.docker#1013]
##### SUMMARY
community.docker.docker_container_copy_into fails when the container is stopped
seems the client is using docker exec to copy, why not use native docker cp functionality?
##### ISSUE TYPE
- Bug Report or feature 

##### COMPONENT NAME
community.docker.docker_container_copy_into

##### ANSIBLE VERSION
```paste below
➜ ansible-playbook --version
ansible-playbook [core 2.18.1]
  config file = None
  configured module search path = ['/Users/x/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/x/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible-playbook
  python version = 3.11.9 (main, Apr  2 2024, 08:25:04) [Clang 15.0.0 (clang-1500.3.9.4)] (/opt/homebrew/opt/python@3.11/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
➜ ansible-galaxy collection list community.docker

# /opt/homebrew/lib/python3.11/site-packages/ansible_collections
Collection       Version
---------------- -------
community.docker 4.1.0
```

##### CONFIGURATION

```paste below
➜ ansible-config dump --only-changed
CONFIG_FILE() = None
PAGER(env: PAGER) = less

GALAXY_SERVERS:
```

##### OS / ENVIRONMENT

Darwin x 24.1.0 Darwin Kernel Version 24.1.0: Thu Oct 10 21:03:15 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T6000 arm64

##### STEPS TO REPRODUCE

```yaml
- name: test
  hosts: x
  become: false
  tasks:
    - name: test
      community.docker.docker_container:
        name: test-nginx
        image: nginx
        command: sh -c "sleep 999999"
        state: present
        recreate: true
    - name: test
      community.docker.docker_container_copy_into:
        path: "/mnt/test.copyme"
        container_path: "/mnt"
        container: "test-nginx"
```

##### EXPECTED RESULTS

to be functionally 

##### ACTUAL RESULTS

```paste below
Cannot execute command in paused container
```
