### ISSUE TITLE
docker_container_exec: Globbing seems not to work when passed in command

### ISSUE THREAD

**Issue by Openuser87** [ansible-collections/community.docker#1031]
##### SUMMARY
Globbing of filenames does not work when passing as argument in `command` or `argv`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`community.docker.docker_container_exec`

##### ANSIBLE VERSION

```paste below
ansible [core 2.18.1]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/semaphore/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/semaphore/apps/ansible/11.1.0/venv/lib/python3.11/site-packages/ansible
  ansible collection location = /home/semaphore/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/semaphore/apps/ansible/11.1.0/venv/bin/ansible
  python version = 3.11.11 (main, Dec  6 2024, 11:15:21) [GCC 13.2.1 20231014] (/opt/semaphore/apps/ansible/11.1.0/venv/bin/python3)
  jinja version = 3.1.5
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection       Version
---------------- -------
community.docker 4.1.0
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = /etc/ansible/ansible.cfg
DEFAULT_LOAD_CALLBACK_PLUGINS(/etc/ansible/ansible.cfg) = True
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = yaml
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False

GALAXY_SERVERS:
```

##### OS / ENVIRONMENT

Executed in semaphore v2.11.2 (running in docker). Target: gitea container in same docker.
Docker version 20.10.24+dfsg1, build 297e128

##### STEPS TO REPRODUCE

Execute following ansible task (provide variables as necessary):

```yaml
    - name: Move backup to mounted volume
      community.docker.docker_container_exec:
        container: "{{ container_name }}"
        command: mv /tmp/gitea-dump-*.zip /data/gitea-dump-{{ timestamp }}.zip
        user: root
```
Other variants tried:
(1)
```yaml
    - name: Move backup to mounted volume
      community.docker.docker_container_exec:
        container: "{{ container_name }}"
        argv:
          - mv
          - /tmp/gitea-dump-*.zip
          - /data/gitea-dump-{{ timestamp }}.zip
        user: root
```
Excerpt from verbose Ansible output (timestams removed):
```
"argv": [
 "mv",
 "/tmp/gitea-dump-*.zip",
 "/data/gitea-dump-2025-01-25-13-47-15.zip"
 ],

...

"rc": 1,
"stderr": "mv: can't rename '/tmp/gitea-dump-*.zip': No such file or directory",
"stderr_lines": [
"mv: can't rename '/tmp/gitea-dump-*.zip': No such file or directory"
],
"stdout": "",
"stdout_lines": []
```

(2)
```yaml
        argv:
          - mv
          - /tmp/gitea-dump-*
          - /data/gitea-dump-{{ timestamp }}.zip
        user: root
```

##### EXPECTED RESULTS

File is moved to target dir and gets the given name.

##### ACTUAL RESULTS

Looks as if the module would pass the path in single quotes, preventing globbing and letting the shell interpret the asterisk verbatim.

```paste below
fatal: [<ip redacted>]: FAILED! => {"changed": true, "rc": 1, "stderr": "mv: can't rename '/tmp/gitea-dump-*.zip': No such file or directory", "stderr_lines": ["mv: can't rename '/tmp/gitea-dump-*.zip': No such file or directory"], "stdout": "", "stdout_lines": []}
```
Note that e.g. following command works directly from shell:
```bash
docker exec -u root -it gitea /bin/bash -c 'mv /tmp/gitea-dump-*.zip /data/gitea-dump-example-timestamp.zip'
```

##### Workaround
This worked well (note: only if there is **one single file** in the source dir):
```yaml
    - name: Move backup to mounted volume
      community.docker.docker_container_exec:
        container: "{{ container_name }}"
        command: /bin/bash -c "mv /tmp/gitea-dump-*.zip /data/gitea-dump-{{ timestamp }}.zip"
        user: root
```
