### ISSUE TITLE
docker_login not working with AWS ECR

### ISSUE THREAD

**Issue by robinelvin** [ansible-collections/community.docker#1048]
##### SUMMARY
My playbook logs into the Docker registry fine but logging into Amazon ECR I get a Permission denied error:

```
TASK [rvm : Log in to Docker registry] **********************************************************************************************************************************
changed: [192.168.1.134]

TASK [rvm : Log in to ECR registry] *************************************************************************************************************************************
fatal: [192.168.1.134]: FAILED! => {"changed": false, "msg": "Error connecting: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))"}
```

**Relevant playbook section**

```yaml
- name: Docker Container
  block:
    - name: Log in to Docker registry
      community.docker.docker_login:
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"
        # Optional parameters
        config_path: "/root/snap/docker/current/.docker/config.json" # Force correct credentials path for snap
        debug: true
        reauthorize: true # Force re-authentication
      become: true

    - name: Log in to ECR registry
      community.docker.docker_login:
        username: AWS
        password: "{{ ecr_login_password }}"
        registry_url: "{{ ecr_registry_url }}"
        # Optional parameters
        config_path: "/root/snap/docker/current/.docker/config.json" # Force correct credentials path for snap
        debug: true
        reauthorize: true # Force re-authentication

```

I am getting the login password via a shell command:

```yaml
- name: Get ECR login password
  ansible.builtin.command:
    cmd: "aws ecr get-login-password"
  register: ecr_login_output
  run_once: true
  delegate_to: localhost

- name: Set ECR password fact
  ansible.builtin.set_fact:
    ecr_login_password: "{{ ecr_login_output.stdout }}"
  run_once: true

- name: Show ECR password fact
  ansible.builtin.debug:
    msg: "ECR login password is {{ ecr_login_password }}"
```

I can see the password in the debug output so I know it is set correctly. If I copy this password and use it manually to log in to ECR it works perfectly. I've also check my access permissions in AWS and I have full administrator access so I don't think this is a permissions issue.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`docker_login`

##### ANSIBLE VERSION

```
ansible [core 2.17.5]
  config file = /Volumes/Crucial X8/Projects/Recyclever/RVMInfrastucture/infrastructure/ansible/ansible.cfg
  configured module search path = ['/Users/rob/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Volumes/Crucial X8/Projects/Recyclever/RVMInfrastucture/infrastructure/.venv/lib/python3.12/site-packages/ansible
  ansible collection location = /Users/rob/.ansible/collections:/usr/share/ansible/collections
  executable location = /Volumes/Crucial X8/Projects/Recyclever/RVMInfrastucture/infrastructure/.venv/bin/ansible
  python version = 3.12.0 (v3.12.0:0fb18b02c8, Oct  2 2023, 09:45:56) [Clang 13.0.0 (clang-1300.0.29.30)] (/Volumes/Crucial X8/Projects/Recyclever/RVMInfrastucture/infrastructure/.venv/bin/python3)
  jinja version = 3.1.4
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection       Version
---------------- -------
community.docker 3.13.0 
```

##### CONFIGURATION

```paste below
CACHE_PLUGIN(/Volumes/Crucial X8/Projects/Recyclever/RVMInfrastucture/infrastructure/ansible/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/Volumes/Crucial X8/Projects/Recyclever/RVMInfrastucture/infrastructure/ansible/ansible.cfg) = facts.json
CONFIG_FILE() = /Volumes/Crucial X8/Projects/Recyclever/RVMInfrastucture/infrastructure/ansible/ansible.cfg
```

##### OS / ENVIRONMENT

Playbook run from Mac OS targetting Ubuntu Core 24 machine.

##### STEPS TO REPRODUCE

```yaml
See above
```

##### EXPECTED RESULTS

I expect it to log in to the registry.

##### ACTUAL RESULTS

```paste below
The full traceback is:
  File "/tmp/ansible_community.docker.docker_login_payload_x86sj860/ansible_community.docker.docker_login_payload.zip/ansible_collections/community/docker/plugins/module_utils/common_api.py", line 117, in __init__
    super(AnsibleDockerClientBase, self).__init__(**self._connect_params)
  File "/tmp/ansible_community.docker.docker_login_payload_x86sj860/ansible_community.docker.docker_login_payload.zip/ansible_collections/community/docker/plugins/module_utils/_api/api/client.py", line 188, in __init__
    self._version = self._retrieve_server_version()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ansible_community.docker.docker_login_payload_x86sj860/ansible_community.docker.docker_login_payload.zip/ansible_collections/community/docker/plugins/module_utils/_api/api/client.py", line 212, in _retrieve_server_version
    raise DockerException(
fatal: [192.168.1.134]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "api_version": "auto",
            "ca_path": null,
            "client_cert": null,
            "client_key": null,
            "config_path": "/root/snap/docker/current/.docker/config.json",
            "debug": true,
            "docker_host": "unix:///var/run/docker.sock",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "reauthorize": true,
            "registry_url": "905417994867.dkr.ecr.eu-west-2.amazonaws.com",
            "ssl_version": null,
            "state": "present",
            "timeout": 60,
            "tls": false,
            "tls_hostname": null,
            "use_ssh_client": false,
            "username": "AWS",
            "validate_certs": false
        }
    },
    "msg": "Error connecting: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))"
}
```
