### ISSUE TITLE
Support -d in docker_compose_v2

### ISSUE THREAD

**Issue by Nounoursdestavernes** [ansible-collections/community.docker#1051]
##### SUMMARY

Hi ! I would be very happy if you would add support for the -d option for docker_compose_v2

This feature would help to keep docker up and running just after a server reboot ;)

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

docker_compose_v2

##### ADDITIONAL INFORMATION

If you have any work around other than using a service or swarm I would take it with pleasure :)

```yaml
- name: Example
  hosts: localhost
  tasks:
    - name: Start detached compose
      community.docker.docker_compose_v2:
        project_src: flask
        state: present
        detached: true
```

PS: I am a bit new to ansible so maybe I am missing something

**Comment by felixfontein** [comment]
The module **always** passes `--detach` to `docker compese up`. I don't think there's a need to disable that, so I don't see why that option is needed.

**Comment by Nounoursdestavernes** [comment]
Hi @felixfontein,

Thanks for your answer, it was clear.  It seems like I have an issue.

This is my docker-compose.yml (This work completely fine on my computer and restart after reboot with a docker compose up -d)

```yaml
name: cyberchef
services:
    cyberchef:
        ports:
            - 127.0.0.1:{{ exposed_port }}:80
        image: ghcr.io/gchq/cyberchef:{{ version }}
        restart: always
```

And this is my ansible playbook:

```yaml
- name: Cyberchef install
  hosts: test
  become: True
  vars:
    username: test
    version: 10.19.4
    exposed_port: 8080
  tasks:
   - name: Create cyberchef folder
     file:
      path: "/home/{{ username }}/cyberchef"
      state: directory
      owner: "{{ username }}"
      group: "{{ username }}"
   - name: Copy dockerfile
     template:
      src: ../templates/docker-compose.yml.j2
      dest: "/home/{{ username }}/cyberchef"
   - name: Pull the docker image
     community.docker.docker_compose_v2_pull:
      project_src: cyberchef
      policy: missing
   - name: Shutdown the docker
     community.docker.docker_compose_v2:
      project_src: cyberchef
      state: absent
   - name: Up the docker
     community.docker.docker_compose_v2:
      project_src: cyberchef
      state: present
```

No error is raised, docker is working in the host machine well but after a restart the docker does'nt restart at all. I must have make a mistake in the playbook if you have any idea I am open !

**Comment by kristianheljas** [comment]
You are not specifying full filename for the compose template, so it will be created as `/home/test/cyberchef/docker-compose.yml.j2` (with **.j2** suffix). I suppose you have older version of the compose file without the suffix.

Also you seem to forgot ownership of the template. You should also specify full paths to the compose tasks as you do before to avoid ambiguity.

Try this:
```yaml
- name: Cyberchef install
  hosts: db
  become: True
  vars:
    username: test
    version: 10.19.4
    exposed_port: 8080
  tasks:

   - name: Create cyberchef folder
     file:
      path: "/home/{{ username }}/cyberchef"
      state: directory
      owner: "{{ username }}"
      group: "{{ username }}"

   - name: Copy dockerfile
     template:
      src: ../templates/docker-compose.yml.j2
      dest: "/home/{{ username }}/cyberchef/docker-compose.yml"
      owner: "{{ username }}"
      group: "{{ username }}"

   - name: Pull the docker image
     community.docker.docker_compose_v2_pull:
      project_src: "/home/{{ username }}/cyberchef"
      policy: missing

   - name: Shutdown the docker
     community.docker.docker_compose_v2:
      project_src: "/home/{{ username }}/cyberchef"
      state: absent

   - name: Up the docker
     community.docker.docker_compose_v2:
      project_src: "/home/{{ username }}/cyberchef"
      state: present
```
