### ISSUE TITLE
Add Docker Bake module

### ISSUE THREAD

**Issue by peanutsguy** [ansible-collections/community.docker#1058]
##### SUMMARY

On Feb 5, 2025, Docker released [Docker Bake](https://www.docker.com/blog/ga-launch-docker-bake/), which simplifies image building. It would be great if we could apply a `docker-bake.hcl` file with Ansible.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

docker_image_bake
docker_bake

##### ADDITIONAL INFORMATION

[Documentation](https://docs.docker.com/build/bake/)

```yaml
- name: Run 'docker buildx bake'
  community.docker.docker_bake:
    files:
      - mybakefile.hcl
      - myoverridefile.hcl
    targets:
      - webapp
      - db
    set:
      - *.tags.version=v1
      - *.platform=linux/arm64
    variables:
      - PORT=7000
```
This example would be akin to running
```bash
PORT=7000 docker buildx bake -f mybakefile.hcl -f myoverridefile.hcl --set *.tags.version=v1 --set *.platform=linux/arm64 webapp db
```
