### ISSUE TITLE
How do I pass the TLS certificate paths correctly?

### ISSUE THREAD

**Issue by VicVerevita** [ansible-collections/community.docker#1063]
##### SUMMARY

When I try to add my certificate paths to an ansible playbook, I get errors saying that "parameters are required together: client_cert, client_key"

I tried with the following ways:

```
      client_cert: 
        cert_path: "/home/user/minden_test/tls-certs/client-cert.pem"
      client_key: 
        key_path: "/home/user/minden_test/tls-certs/client-key.pem"
```
```
      client_cert: "/home/user/minden_test/tls-certs/client-cert.pem"
      client_key: "/home/user/minden_test/tls-certs/client-key.pem"
```
```
      client_cert:
        cert_path: "/home/user/minden_test/tls-certs/client-cert.pem"  # Path to client certificate
        key_path: "/home/user/minden_test/tls-certs/client-key.pem"  # Path to client key
```

None of them seem to be working. What am I doing wrong?

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

    group/community.docker.docker:

##### ANSIBLE VERSION

```paste below
    quay.io/ansible/awx-ee:latest
```
