### ISSUE TITLE
Support re-tagging docker image

### ISSUE THREAD

**Issue by Yajo** [ansible-collections/community.docker#147]
##### SUMMARY

I need to retag an image, or to issue this command, basically: `docker image tag $source $destination`. No way to do it with `community.docker.docker_image` AFAICS.

The purpose is to roll back to an older image after a failed deployment.

##### ISSUE TYPE
- The `source` argument doesn't allow specifying a different image as source.
- A new `local_source` may help.

##### COMPONENT NAME

docker_image

##### ADDITIONAL INFORMATION

```yaml
- name: re-tag old image
  community.docker.docker_image:
    source: local
    local_source: "{{ old_image }}"
    force_tag: yes
    name: deployed/image/name:tag
```
