### ISSUE TITLE
docker_container: mount CIFS share

### ISSUE THREAD

**Issue by asdfwertde** [ansible-collections/community.docker#175]
##### SUMMARY
Hey, I'm trying to set up a cifs mount according to https://docs.docker.com/storage/volumes/#create-cifssamba-volumes but `source` is a required parameter for `mounts` entries, although it is not needed in this case.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
docker_container

##### ANSIBLE VERSION
```
ansible [core 2.11.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/xxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/xxx/docker_cifs_test/ansible_venv/lib/python3.8/site-packages/ansible
  ansible collection location = /home/xxx/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/xxx/docker_cifs_test/ansible_venv/bin/ansible
  python version = 3.8.5 (default, May 27 2021, 13:30:53) [GCC 9.3.0]
  jinja version = 3.0.1
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection        Version
----------------- -------
community.general 3.3.0
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

Run a task for a docker container that mounts a cifs share.

```yaml
- name: Docker container with cifs mount
    docker_container:
      name: cifs_test
      image: alpine
      command: sleep infinity
      mounts:
        - target: /mnt/cifs_test
          volume_driver: local
          volume_options:
            type: cifs
            device: //cifs_share_server/some/dir
            o: addr=cifs_share_server,user=cifs_user,password=cifs_user_pass,domain=some.domain,vers=2.0
```

##### EXPECTED RESULTS

The docker container is created with the specified mount.

##### ACTUAL RESULTS

Ansible fails because `source` is a required parameter.

```paste below
fatal: [xxx.xxx.xxx.xxx]: FAILED! => {"changed": false, "msg": "source must be specified for mount \"/mnt/cifs_test\" of type \"volume\""}
```
I can get around this by setting `source` to an empty string:
```yaml
- name: Docker container with cifs mount
    docker_container:
      name: cifs_test
      image: alpine
      command: sleep infinity
      mounts:
        - target: /mnt/cifs_test
          source: ""
          volume_driver: local
          volume_options:
            type: cifs
            device: //cifs_share_server/some/dir
            o: addr=cifs_share_server,user=cifs_user,password=cifs_user_pass,domain=some.domain,vers=2.0
```
But then the container gets recreated every time I run the playbook:
```
{
     "expected_mounts": [
         {
...
-            "source": null,
+            "source": "",
...
```
In [the source code](https://github.com/ansible-collections/community.docker/blob/main/plugins/modules/docker_container.py#L2009) I see that there is an exception for the mount type `tmpfs`, maybe there needs to be another exception for mount type `volume` if the volume option `type` is set to `cifs`
