### ISSUE TITLE
docker_host_info: Filter containers by multiple labels

### ISSUE THREAD

**Issue by Yajo** [ansible-collections/community.docker#18]
##### SUMMARY

Cannot filter for multiple labels.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

docker_host_info

##### ADDITIONAL INFORMATION

This cannot work because we can't define the same key twice in a dict:

```yaml
- name: find running docker containers
  register: docker_info
  docker_host_info:
    containers: yes
    containers_filters:
      label: com.docker.compose.project=myproject # THIS GETS IGNORED
      label: com.docker.compose.service=backup
```

Possible solutions:

1.  Allow a list in `containers_filters`:

    ```yaml
    - name: find running docker containers
      register: docker_info
      docker_host_info:
        containers: yes
        containers_filters:
          - label=com.docker.compose.project=myproject
          - label=com.docker.compose.service=backup
    ```

1.  Allow a dict in `containers_filters.label` filter:

    ```yaml
    - name: find running docker containers
      register: docker_info
      docker_host_info:
        containers: yes
        containers_filters:
          label:
            com.docker.compose.project: myproject
            com.docker.compose.service: backup
    ```

I have not tested, but I guess the same applies to `images_filters`, `networks_filters` and `volumes_filters`.
