### ISSUE TITLE
docker_compose: `changed` always true when `profiles` are present

### ISSUE THREAD

**Issue by hummeltech** [ansible-collections/community.docker#191]
##### SUMMARY

When using a `docker-compose` definition containing a `service` with a `profiles` specification, the value of `changed` is always `true`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

plugins/modules/docker_compose.py

##### ANSIBLE VERSION

```shell
$ ansible --version
ansible [core 2.11.3] 
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = ~/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.6 (default, Jun 30 2021, 10:22:16) [GCC 11.1.0]
  jinja version = 3.0.1
  libyaml = True
```

##### COLLECTION VERSION

```shell
$ ansible-galaxy collection list community.docker

# /usr/lib/python3.9/site-packages/ansible_collections
Collection       Version
---------------- -------
community.docker 1.9.0
```

##### CONFIGURATION

```shell
$ ansible-config dump --only-changed

```

##### STEPS TO REPRODUCE

Run the example playbook below two times:

```YAML
---
- name: Error when using profiles
  hosts: localhost
  gather_facts: no
  tasks:
    - community.docker.docker_compose:
        debug: true
        project_name: example
        definition:
          version: '2'
          services:
            db:
              image: postgres:latest
              environment:
                POSTGRES_PASSWORD: example
            web:
              image: httpd:latest
              depends_on:
                - db
            p_web:
              image: httpd:latest
              depends_on:
                - db
              profiles:
                - p
      register: example_output

    - ansible.builtin.debug:
        var: example_output.actions

    - ansible.builtin.assert:
        that:
          - not example_output.changed

    - ansible.builtin.assert:
        that:
          - example_output.services.db.example_db_1.state.running
          - example_output.services.web.example_web_1.state.running
          - not example_output.services.p_web
```

##### EXPECTED RESULTS

There should be no changes after the first run of the playbook above.

##### ACTUAL RESULTS

It is always `changed`.

```JSON
changed: [localhost] => {
    "actions": [
        {
            "create": [],
            "service": "p_web"
        }
    ],
    "changed": true,
    "invocation": {
        "module_args": {
            "api_version": "auto",
            "build": false,
            "ca_cert": null,
            "client_cert": null,
            "client_key": null,
            "debug": true,
            "definition": {
                "services": {
                    "db": {
                        "environment": {
                            "POSTGRES_PASSWORD": "example"
                        },
                        "image": "postgres:latest"
                    },
                    "p_web": {
                        "depends_on": [
                            "db"
                        ],
                        "image": "httpd:latest",
                        "profiles": [
                            "p"
                        ]
                    },
                    "web": {
                        "depends_on": [
                            "db"
                        ],
                        "image": "httpd:latest"
                    }
                },
                "version": "2"
            },
            "dependencies": true,
            "docker_host": "unix://var/run/docker.sock",
            "env_file": null,
            "files": null,
            "hostname_check": false,
            "nocache": false,
            "profiles": null,
            "project_name": "example",
            "project_src": null,
            "pull": false,
            "recreate": "smart",
            "remove_images": null,
            "remove_orphans": false,
            "remove_volumes": false,
            "restarted": false,
            "scale": null,
            "services": null,
            "ssl_version": null,
            "state": "present",
            "stopped": false,
            "timeout": 10,
            "tls": false,
            "tls_hostname": null,
            "use_ssh_client": false,
            "validate_certs": false
        }
    },
    "services": {
        "db": {
            "example_db_1": {
                "cmd": [
                    "postgres"
                ],
                "image": "postgres:latest",
                "labels": {
                    "com.docker.compose.config-hash": "1ab83594a4d5cc2746e95d0ca3ad3954d0bf47163384b5cb9386e73088c2e413",
                    "com.docker.compose.container-number": "1",
                    "com.docker.compose.oneoff": "False",
                    "com.docker.compose.project": "example",
                    "com.docker.compose.project.config_files": "/tmp/ansibleaj7s34_n/docker-compose.yml",
                    "com.docker.compose.project.working_dir": "/tmp/ansibleaj7s34_n",
                    "com.docker.compose.service": "db",
                    "com.docker.compose.version": "1.29.2"
                },
                "networks": {
                    "example_default": {
                        "IPAddress": "172.28.0.2",
                        "IPPrefixLen": 16,
                        "aliases": [
                            "db",
                            "c645eeb3a4a7"
                        ],
                        "globalIPv6": "",
                        "globalIPv6PrefixLen": 0,
                        "links": null,
                        "macAddress": "02:42:ac:1c:00:02"
                    }
                },
                "state": {
                    "running": true,
                    "status": "running"
                }
            }
        },
        "p_web": {},
        "web": {
            "example_web_1": {
                "cmd": [
                    "httpd-foreground"
                ],
                "image": "httpd:latest",
                "labels": {
                    "com.docker.compose.config-hash": "e8031049ec6c1362eeccde82c6cd569f8b7fb3e459434380885684a528b7fe37",
                    "com.docker.compose.container-number": "1",
                    "com.docker.compose.oneoff": "False",
                    "com.docker.compose.project": "example",
                    "com.docker.compose.project.config_files": "/tmp/ansiblew7q1cip3/docker-compose.yml",
                    "com.docker.compose.project.working_dir": "/tmp/ansiblew7q1cip3",
                    "com.docker.compose.service": "web",
                    "com.docker.compose.version": "1.29.2"
                },
                "networks": {
                    "example_default": {
                        "IPAddress": "172.28.0.3",
                        "IPPrefixLen": 16,
                        "aliases": [
                            "3324579e6f0c",
                            "web"
                        ],
                        "globalIPv6": "",
                        "globalIPv6PrefixLen": 0,
                        "links": null,
                        "macAddress": "02:42:ac:1c:00:03"
                    }
                },
                "state": {
                    "running": true,
                    "status": "running"
                }
            }
        }
    }
}
```
