### ISSUE TITLE
Running local ansible to create local docker Image

### ISSUE THREAD

**Issue by sathishsoundharajan** [ansible-collections/community.docker#196]
##### SUMMARY

Running local ansible to create local docker Image, image creation fails but ansible takes it as success.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

docker-image

##### ANSIBLE VERSION

```paste below
ansible [core 2.11.4]
  config file = None
  configured module search path = ['/Users/ecom-sathish.sa/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/ecom-sathish.sa/.ansible/collections:/usr/share/ansible/collections
  executable location = /Library/Frameworks/Python.framework/Versions/3.9/bin/ansible
  python version = 3.9.7 (v3.9.7:1016ef3790, Aug 30 2021, 16:25:35) [Clang 12.0.5 (clang-1205.0.22.11)]
  jinja version = 3.0.1
  libyaml = True
```

##### COLLECTION VERSION

```paste below
No collection. 
```

##### CONFIGURATION

```paste below
N/A
```

##### OS / ENVIRONMENT

Mac OS BigSur

##### STEPS TO REPRODUCE

```
Directory Structure

build
├── docker-compose.dev.yml
├── playbooks
│   ├── deploy-deps.yml
│   └── setup-local-registry.yml
├── postgres
│   └── DockerFile
└── rabbitmq
    ├── DockerFile
    └── init.sh
deploy-scripts
├── db-schema
│   └── global
│       ├── 01-init.sql
│       ├── 02-tables.sql
│       ├── 03-grant.sql
│       └── 04-index.sql
├── rabbitmq
│   └── global
│       └── prepare-queues.sh

```

```yaml
- hosts: localhost
  vars:
    registry_host: "localhost"
    registry_port: 5000
    i_postgres_image: "orderpostgres"
  tasks:
    - name: "Create & Push Postgres Image"
      docker_image:
        name: "{{ i_postgres_image  }}"
        build:
          path: "../../build/postgres"
        source: build
        state: present
      register: "out"
    - name: Show test output
      debug:
        msg: "{{ out }}"
```

My Postgres DockerFile

```
FROM postgres:10.17-buster
COPY ../scripts/db-schema/ /docker-entrypoint-initdb.d/

```
When i execute ansible-playbook from the project root directory, this is result of the execution.

```
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [localhost] ***********************************************************************************************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Create & Push Postgres Image] ****************************************************************************************************************************************************************************
changed: [localhost]

TASK [Show test output] ****************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": {
        "actions": [
            "Built image orderpostgres:latest from ../../build/postgres"
        ],
        "changed": true,
        "failed": false,
        "image": null,
        "stdout": "",
        "stdout_lines": []
    }
}

PLAY RECAP *****************************************************************************************************************************************************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

Based on the output i expected the docker image is built and ready to pushed to local registry. But when i execute, docker images i'm not seeing that image at all.

```
docker images
REPOSITORY   TAG       IMAGE ID       CREATED      SIZE
registry     2         b2cb11db9d3d   3 days ago   26.2MB
```

My analysis until now.

My DockerFile has to copy some scripts from the root path of the project that is the reason it has "../scripts/db-schema". I cannot change this path because the same DockerFile is being used docker-compose.dev.yml file inside build directly for creating dev containers.

I am guessing docker image creation failing, but ansible module does not throw error and provides output as success.

Second, ansible docker module does not have config to customize the build context like how docker-compose allows in the yml.

Here is my docker-compose.dev.yml for reference

```
version: '3'
services:

  redis:
    image: redis:5.0
    container_name: 'cache'
    ports: 
      - 6379:6379
    volumes: 
      - ~/.docker-volume/redis/data/:/var/lib/redis

  postgres:
    build:
      context: ../
      dockerfile: ./build/postgres/DockerFile
    container_name: 'database'
    restart: always
    environment:
      - POSTGRES_USER=haha
      - POSTGRES_PASSWORD=haha
      - POSTGRES_DB=haha
    logging:
      options: 
        max-size: 10m
        max-file: '3'
    ports: 
      - 5432:5432
    volumes: 
      - ~/.docker-volume/postgres/data/:/var/lib/postgresql/data
```

My Questions:

1. How can i solve this problem ? Without rearranging possible and not changing the existing DockerFile
2. How to configure ansible docker module to the custom context ?
3. Why is ansible docker module is not throwing error ?

##### ACTUAL RESULTS

```paste below

```
FYI: https://stackoverflow.com/questions/69057345/running-local-ansible-to-create-local-docker-image
