### ISSUE TITLE
configs and secrets info

### ISSUE THREAD

**Issue by mario-slowinski** [ansible-collections/community.docker#204]
##### SUMMARY
Get details about already existing docker objects
* configs
* secrets

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
* `community.docker.docker_config_info`
* `community.docker.docker_secret_info`

##### ADDITIONAL INFORMATION
Hello

Please consider adding module to get details/data about docker **configs** and **secrets** or incorporate this functionality into existing module (i.e. `community.docker.docker_host_info`)

```yaml
- name: Get the docker config details
  community.docker.docker_config_info:
    name: "config_name or id"
  register: result
```
```yaml
- name: Get the docker secret details
  community.docker.docker_secret_info:
    name: "secret_name or id"
  register: result
```
and/or
```yaml
community.docker.docker_host_info:
  configs: true
  secrets: true
register: result
```
```yaml
- ansible.builtin.debug:
    var: result.config
```
