### ISSUE TITLE
Set env key value pairs on docker compose

### ISSUE THREAD

**Issue by klemmchr** [ansible-collections/community.docker#205]
##### SUMMARY

The `docker_container` module allows to [set environment variables via key value pairs](https://docs.ansible.com/ansible/latest/collections/community/docker/docker_container_module.html#parameter-env). The `docker_compose` module is missing this functionality.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
`docker_compose`

##### ADDITIONAL INFORMATION

My goal is to set environment variables with values taken from ansible variables. In my playbook I'm reading secrets out of a key vault and want to set their respective values to environment variables in my docker compose file. At the moment I would need to create an `.env` file which is tedious. 

This would be my desired method to set them (which matches the syntax of `docker_container`)

```yaml
- name: Restart a container
  community.docker.docker_compose:
      # ...
      env:
          MY_ENV_VAR: "{{ my_var | string }}"
```

**Comment by felixfontein** [comment]
Does docker-compose allow you to do that on the command line? If not, I don't see how this should work.

**Comment by klemmchr** [comment]
AFAIK `docker-compose up` does not support env files on the command line either. So I would guess that there is also some trickery in place to make that work.

**Comment by clgx-pbogdan** [comment]
Docker-compose allows to use --env-file PATH in command line (at least in version 1.29.2) and env_file is supporting in docker_compose module but env parameter is not supported in docker_compose module and it'll be great if maintainers will add this support. 
Regarding env parameter we can use it in our docker-compose.yml but not in command line.

**Comment by felixfontein** [comment]
The module utilizes docker-compose, so if docker-compose only allows to specify env variables via `--env-file` and docker-compose.yml, I don't see how the module can support another way to provide environment variables.

**Comment by klemmchr** [comment]
Then as a workaround, is there some module that allows to write key/value pairs to an .env file?

**Comment by Ajpantuso** [comment]
I think there's some confusion here between the `docker_container` module and `docker_compose` module. In the context of `docker_compose` environment variables passed to containers are always described within the compose yaml (see [here](https://docs.docker.com/compose/environment-variables/#set-environment-variables-in-containers)). The `.env` file and environment variables passed from the shell when invoking the `docker-compose` command on the other hand are used to substitute variables within the compose yaml itself. So to pass environment variables from an `Ansible` task to the container you would need two levels of references.

In Ansible:
```yaml
- name: Example of variables passed to containers
  environment:
    SOME_VAR: "{{ some_var_value }}"
  community.docker_compose:
  ...
```

In compose yaml:
```yaml
version: '2'
services:
  some_service:
    environment:
      - SOME_VAR # Passing the variable by name causes the value to be taken from the shell's environment if defined.
...
```
Hope that helps.
