### ISSUE TITLE
Option to get container ID and/or volume details from docker_compose module

### ISSUE THREAD

**Issue by joao-p-marques** [ansible-collections/community.docker#207]
##### SUMMARY
The `docker_compose` module returns a lot of useful information, like container labels and networks. It would be useful to also get the information associated to the volumes from each container (name, mount point, etc.) Alternatively, and in addition, having the container ID, besides the name, could also help on some other tasks in the playbook.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

It would be a part of the existing `docker_compose` module.

##### ADDITIONAL INFORMATION

For example, instead of:
```yaml
- name: "Start containers"
  docker_compose:
    project_src: "{{ project_path }}"
    state: present

- name: "know currently-serving container id for service X"
  command:
    argv:
      - docker-compose
      - ps
      - --quiet
      - X
    chdir: "{{ project_path }}"
  register: serving_id
  changed_when: false

- name: "obtain container details for X"
  community.docker.docker_container_info:
    name: "{{ serving_id.stdout }}"
  register: x_container_data

- name: "obtain Y volume details for container X"
  set_fact:
    x_volume_y: |-
      {{
        x_container_data.container.Mounts
        |selectattr('Type', 'equalto', 'volume')
        |selectattr('Name', 'search', '^y$')
        |first
      }}
```

We could do:

```yaml
- name: "Start containers"
  docker_compose:
    project_src: "{{ project_path }}"
    state: present
  register: container_data

- name: "obtain Y volume details for container X"
  set_fact:
    x_volume_y: |-
      {{
        container_data.services.X.volumes.Mounts
        |selectattr('Type', 'equalto', 'volume')
        |selectattr('Name', 'search', '^y$')
        |first
      }}
```
(or something similar, this is sort of pseudo-code)

ping @Yajo
