### ISSUE TITLE
In swarm service module "command" parameter not corresponds to docker swarm service create command

### ISSUE THREAD

**Issue by smirninini** [ansible-collections/community.docker#212]
For example of starting docker container, [node-exporter ](https://github.com/prometheus/node_exporter)

```
docker_swarm_service:
    name: node-exporter
    image: prom/node-exporter:latest
    command:
      - '--path.rootfs=/host'
    mode: global
    networks:
      - monitoring
    mounts:
      - source: /
        target: /host
        type: bind
        readonly: true
        propagation: rslave
```

there will be an error `"Error": "OCI runtime create failed: container_linux.go:380: starting container process caused: exec: \"--path.rootfs=/host\": stat --path.rootfs=/host: no such file or directory: unknown"`

Starting from CLI `docker service create --mode global --network monitoring --mount type=bind,bind-propagation=rslave,src=/,destination=/host,ro  --name node-exporter prom/node-exporter:latest "--path.rootfs=/host"` will work correctly. 

How I can solve this problem?
