### ISSUE TITLE
docker-compose 2.0.0 is no longer written in Python, thus breaking the docker_compose module

### ISSUE THREAD

**Issue by felixfontein** [ansible-collections/community.docker#216]
##### SUMMARY
I guess we have to mention in the requirements of the module that it needs docker-compose < 2.0.0. Potentially we either have to adjust the module to also work with docker-compose 2.0.0 and newer, or we have to deprecate it.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
docker_compose

**Comment by felixfontein** [comment]
CC @aminvakil thanks for reporting this! (BTW the PR you mentioned is unrelated to this.)

**Comment by felixfontein** [comment]
Adding a warning and the < 2.0.0 requirement in #217.

**Comment by dmp1ce** [comment]
Should I expect that this module will be updated to support version 2.0.0 and greater of Compose? I'm trying to figure out if I should rewrite my docker-compose sections of my playbook or just wait for an update.

**Comment by felixfontein** [comment]
@dmp1ce that depends on whether someone wants to rewrite the docker_compose module in such a way that it will simply work with the CLI. Right now the module depends on importing the Python code of docker-compose itself, which only works for docker-compose < 2.0.0 since for 2.0.0 docker-compose was rewritten in Go.

**Comment by libricoleur** [comment]
This has become a problem on distros that already updated to compose v2, such as Arch Linux. Has anyone started working on a port of the module?

In the meantime I installed v1 from pip in a virtualenv and pointed the PYTHONPATH environment variable to it.

**Comment by felixfontein** [comment]
I'm not aware of anyone working on this.

**Comment by dmp1ce** [comment]
@libricoleur I just created my own tasks which copy the `docker-compose.yml` to the machine and then run `docker-compose`. It looks something like this:

```

- name: Loop through starting Docker services (manually)
  block:
    - name: Copy docker-compose templates for each service
      ansible.builtin.template:
        src: files/docker_services/{{ item.project_name }}.yml.j2
        dest: /home/maintenance/docker_services/{{ item.project_name }}/docker-compose.yml
        backup: yes
      loop: "{{ docker_services }}"

    - name: "Update docker service image"
      command:
        chdir: /home/maintenance/docker_services/{{ item.project_name }}
        cmd: docker-compose pull
      loop: "{{ docker_services }}"
    - name: "Start docker service"
      command:
        chdir: /home/maintenance/docker_services/{{ item.project_name }}
        cmd: docker-compose up -d
      loop: "{{ docker_services }}"
  when: docker_services is defined
```

I have a feeling it might be awhile before this issue gets resolved, so I hope this work around helps some people.

**Comment by craph** [comment]
Any updates on this subject ?

**Comment by felixfontein** [comment]
Unfortunately nobody wanted to work on this so far, so no, there are no news.

**Comment by Sid-Sun** [comment]
Hi, I am working on create a new compose v2 module by using python on whales (thanks to @gotmax23 for pointing out [python-on-whales in #364](https://github.com/ansible-collections/community.docker/issues/364#issuecomment-1201286665)) - is there any interest in implementing that in `community.docker`? Thanks

**Comment by felixfontein** [comment]
Since folks have been repeatedly asking for this: yes, there is an interest in that.

(I personally don't think that using python-on-whales is a good idea, since you can also simply run the `docker-compose` binary directly without using a third-party library for that and forcing all users of the module to install that library. But since I'm neither writing nor maintaining that module, I don't care that much :) )

**Comment by felixfontein** [comment]
For everone interested, there's now a PR: #540

**Comment by goldyfruit** [comment]
@felixfontein thanks for this PR, I hope to see it merge soon.
Just had a limitation due to `docker-compose`. _c.f:_  https://github.com/docker/compose/issues/9505

**Comment by septatrix** [comment]
Funnily enough `podman-compose` is what I have now been using with `--podman-path docker` and `--podman-args compose` such that in invokes `docker compose` instead of `podman` :D

**Comment by ptr727** [comment]
Apologies for being a bit off-topic, please redirect as appropriate.  
I tried using compose, failed, found that v < 2.0, found this.

I just need rudimentary inter-container startup/restart behavior, that will be honored by portainer stacks and and watchtower updates.  
Other than using compose, is there another way to specify inter-instance dependencies using the normal container module options?

**Comment by cdauth** [comment]
This is driving me crazy. Has anyone managed to get this to run?

I have installed docker-compose to a virtual env using `pip`, but Ansible keeps telling me that there is `No module named 'compose'`. I've tried adding the virtual env to my `PATH` using the `environment` property in my playbook configuration, but it does not help.

**Comment by felixfontein** [comment]
@cdauth you have to point ansible to the Python interpreter of that venv - then it should work. (At least for the docker_compose tasks - `ansible_python_interpreter` should help here.)

**Comment by cdauth** [comment]
Thanks! This is how I installed the pip module on the server:
```yaml
- pip:
    name: docker-compose
    virtualenv: /usr/local/pip
```

And this is how I configured my playbook to use the virtual env:
```yaml
    vars:
        ansible_python_interpreter: /usr/local/pip/bin/python
```
