### ISSUE TITLE
Scaling via docker-compose.yml does not seem to work

### ISSUE THREAD

**Issue by fabiante** [ansible-collections/community.docker#234]
##### SUMMARY
I set the `scale` property of a docker-compose file via templating and expect this plugin to call `docker-compose up` in such a way that new instances are created / unwanted removed.

##### ISSUE TYPE
Bug

##### COMPONENT NAME
community.docker.docker_compose

##### ANSIBLE VERSION

```paste below
ansible [core 2.11.6] 
  config file = /home/fabian/git/ansible-docker/ansible.cfg
  configured module search path = ['/home/fabian/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/fabian/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]
  jinja version = 2.10.1
  libyaml = True
```

##### COLLECTION VERSION
```paste below
# /usr/lib/python3/dist-packages/ansible_collections
Collection       Version
---------------- -------
community.docker 1.10.0
```

##### CONFIGURATION

```paste below
-
```

##### OS / ENVIRONMENT

The target machine runs on Debian 10, has docker and docker compose installed and they work fine, both manually and automated.

##### STEPS TO REPRODUCE

This is essentially the `docker-compose.yml` copied to the target with two variables.

```yaml
version: "3"

services:
  worker:
    image: {{ worker_img }}
    restart: always
    scale: {{ worker_instances }}
```

```yml
- name: docker-compose up worker (with pull)
  community.docker.docker_compose:
    project_src: "/root/project"
    files:
      - "docker-compose.yml"
    services:
      - worker
    state: present
    restarted: no
    stopped: no
    build: no 
    pull: yes
    remove_orphans: yes
    remove_volumes: no

- name: docker-compose up all services (without pull)
  community.docker.docker_compose:
    project_src: "/root/project"
    files:
      - "docker-compose.yml"
    state: present
    restarted: no
    stopped: no
    build: no 
    pull: no
    remove_orphans: yes
    remove_volumes: no
```

##### EXPECTED RESULTS
I expect that changing the ansible var `worker_instances` would result in new containers being created / unwanted removed.

##### ACTUAL RESULTS
The amount of containers does not change. When I manually run `docker-compose up -d` on the target host, the scaling works as expected.

Therefore I suspect that either I use some variables wrong the docker-compose command is not build correctly.
