### ISSUE TITLE
docker_container_exec's stdin syntax doesn't decrypt vaulted variables.

### ISSUE THREAD

**Issue by kenorb** [ansible-collections/community.docker#241]
##### SUMMARY

Using docker_container_exec's stdin syntax doesn't decrypt vaulted variables.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible [core 2.11.6]
  python version = 3.9.7 (default, Sep 10 2021, 14:59:43) [GCC 11.2.0]
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION

```paste below
$ ansible-galaxy collection list | grep docker
community.docker              1.10.0 
community.docker 1.9.0  
```

##### OS / ENVIRONMENT

- Target OS: Ubuntu

##### STEPS TO REPRODUCE

```yaml
    - name: Upload key
      community.docker.docker_container_exec:
        argv:
          - tee
          - secret.json
        container: '{{ docker_id }}'
        stdin: '{{ secret_data | to_json }}'
```

Var file (vaulted value is embedded):

```
secret_data:
  priv_key:
    value: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        1161...
        ....
  pub_key:
    value: some_public_key
```

##### EXPECTED RESULTS

Vaulted variable is properly decrypted.

I've tested encryption with:

```
ansible localhost -m ansible.builtin.debug -a var=secret_data -e @all/vars.yml
```

and the syntax is valid (variable is decrypted as expected), but not when using docker collection.

##### ACTUAL RESULTS

JSON file which was created consist ansible vault data, not decrypted string.

```paste below
"value": {"__ansible_vault": "$ANSIBLE_VAULT;1.1;AES256;\n1161...
```
