### ISSUE TITLE
--no-build argument for Docker Compose

### ISSUE THREAD

**Issue by moqmar** [ansible-collections/community.docker#252]
##### SUMMARY

We're using the same Docker Compose files for development and deployment, with both `image` and `build` being set - on deployment (using Ansible), it shouldn't try to build anything but always pull the latest version from the registry.

This works with the `docker compose up --no-build ...` option, but that doesn't seem to be supported by the docker-compose module.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

community.docker.docker_compose

##### ADDITIONAL INFORMATION

I'd suggest to add "build: never" as an option - just as `build: yes` is equivalent to `--build` and `build: no` is equivalent to not specifying any parameter, `build: never` could be equivalent to `--no-build`.

```yaml
- name: Create and start services
  community.docker.docker_compose:
    project_src: flask
    build: never
```
