### ISSUE TITLE
Print container output?

### ISSUE THREAD

**Issue by mangkoran** [ansible-collections/community.docker#274]
How do I print the output of container? Currently I have these lines in my playbook and it won't print:
```yaml
    - name: Create and start default Docker container
      docker_container:
        name: hello-world-1
        image: hello-world
        auto_remove: true
        output_logs: true
        state: started
```

**Comment by felixfontein** [comment]
You need to set [detach=false](https://docs.ansible.com/ansible/latest/collections/community/docker/docker_container_module.html#parameter-detach), otherwise there is nothing to return. (Also whether this is printed depends on your callback plugin. In general you have to register the result and output it.)

**Comment by mangkoran** [comment]
After change the lines to these:
```yaml
    - name: Create and start default Docker container
      docker_container:
        name: hello-world-1
        image: hello-world
        cleanup: true
        detach: false
        output_logs: true
        state: started
      register: docker

    - name: Debug
      debug:
        var: docker
```
It prints the output. Thank you!
