### ISSUE TITLE
Docker_container: "Link" prepends a '\' on path

### ISSUE THREAD

**Issue by sandersac** [ansible-collections/community.docker#284]
##### SUMMARY
Good day,

While cleaning up outputs of my ansible notebook I noticed that a nextcloud deployment through docker_container always returned "changed" status instead of being idempotent on repeat runs. I include the source code and --diff output below. In short though, I suspect the "link" option of docker_container is prepending a \ to the path, thus causing Ansible to think the container is being linked to a new location (even though it'll go to the same spot later).

I am a bit of an ansible noob though, so there could be something else wrong here. If so, I'm more than happy to provide more source code to help diagnose the issue.

Thank you for the hard work done on Ansible in general, and the docker_container module in particular. Working with it has been a breeze and it is quickly becoming a tool I depend on more and more.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
docker_container

##### ANSIBLE VERSION
```paste below
ansible 2.9.27
  config file = /home/username/Desktop/ansible/ansible.cfg
  configured module search path = ['/home/username/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.10.1 (main, Dec  9 2021, 00:00:00) [GCC 11.2.1 20211203 (Red Hat 11.2.1-7)]
```

I also recently installed the pip version of Ansible and have the same issue:
```
ansible [core 2.12.1]
  config file = /home/username/Desktop/ansible/ansible.cfg
  configured module search path = ['/home/username/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/username/Desktop/ansible/ansible/lib/python3.10/site-packages/ansible
  ansible collection location = /home/username/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/username/Desktop/ansible/ansible/bin/ansible
  python version = 3.10.1 (main, Dec  9 2021, 00:00:00) [GCC 11.2.1 20211203 (Red Hat 11.2.1-7)]
  jinja version = 3.0.3
  libyaml = True
```

##### CONFIGURATION
```paste below
DEFAULT_HOST_LIST(/home/username/Desktop/ansible/ansible.cfg) = ['/home/username/Desktop/ansible/inventory.yml']
DEFAULT_LOAD_CALLBACK_PLUGINS(/home/username/Desktop/ansible/ansible.cfg) = True
DEFAULT_STDOUT_CALLBACK(/home/username/Desktop/ansible/ansible.cfg) = yaml
DISPLAY_SKIPPED_HOSTS(/home/username/Desktop/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/home/username/Desktop/ansible/ansible.cfg) = auto
```

##### OS / ENVIRONMENT
Fedora 35

##### STEPS TO REPRODUCE
Run the playbook twice which includes this role. The first time I'll see a change on mariaDB/Nextcloud tasks as expected. The second time I shouldn't see any changes at all.

```yaml
---
- name: Include variables
  include_vars: secrets.yml

- name: Deploy MariaDB server
  docker_container:
    image: mariadb
    name: mariadb
    restart_policy: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    volumes:
      - "{{db_volume}}:/var/lib/mysql"
    env:
      MYSQL_ROOT_PASSWORD: "{{sql_root_pass}}"
      MYSQL_PASSWORD: "{{sql_pass}}"
      MYSQL_DATABASE: db
      MYSQL_USER: "{{sql_user}}"

- name: Deploy Nextcloud
  docker_container:
    image: nextcloud
    name: nextcloud
    restart_policy: always
    ports:
      - "8080:80"
    links:
      - "{{db_volume}}:/var/lib/mysql"
    volumes:
      - "{{nextcloud}}:/var/www/html"
    env:
      MYSQL_PASSWORD: "{{sql_pass}}"
      MYSQL_DATABASE: db
      MYSQL_USER: "{{sql_user}}"
      MYSQL_HOST: mariadb
```

##### EXPECTED RESULTS
No changes, rerunning the command should be idempotent.

##### ACTUAL RESULTS
Task is logged as "changed"

```paste below
TASK [nextcloud : Deploy Nextcloud] **********************************************************************************
--- before
+++ after
@@ -1,3 +1,3 @@
 expected_links:
-- /mariadb:/nextcloud/var/lib/mysql
+- /mariadb:/nextcloud//var/lib/mysql
 running: true
```
