### ISSUE TITLE
docker_container with strict labels comparison ignores base image labels

### ISSUE THREAD

**Issue by RoGryza** [ansible-collections/community.docker#314]
##### SUMMARY

When using docker_container to run a container with non-empty `labels`, if its base image also defines labels and labels comparison is set to `strict` the container gets changed.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`docker_container`

##### ANSIBLE VERSION

```paste below
ansible [core 2.12.3]
  config file = /home/rogryza/code/GitHub/RoGryza/ansible-docker-labels-strict/ansible.cfg
  configured module search path = ['/home/rogryza/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/rogryza/code/GitHub/RoGryza/ansible-docker-labels-strict/.direnv/python-3.10.2/lib/python3.10/site-packages/ansible
  ansible collection location = /home/rogryza/code/GitHub/RoGryza/ansible-docker-labels-strict
  executable location = /home/rogryza/code/GitHub/RoGryza/ansible-docker-labels-strict/.direnv/python-3.10.2/bin/ansible
  python version = 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0]
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /home/rogryza/code/GitHub/RoGryza/ansible-docker-labels-strict/ansible_collections
Collection       Version
---------------- -------
community.docker 2.3.0  

# /home/rogryza/code/GitHub/RoGryza/ansible-docker-labels-strict/.direnv/python-3.10.2/lib/python3.10/site-packages/ansible_collections
Collection       Version
---------------- -------
community.docker 2.2.1  
```

##### CONFIGURATION

```paste below
COLLECTIONS_PATHS(/home/rogryza/code/GitHub/RoGryza/ansible-docker-labels-strict/ansible.cfg) = ['/home/rogryza/code/GitHub/RoGryza/ansible-docker-labels-strict']
```

##### OS / ENVIRONMENT

Observed in `archlinux` and `Ubuntu 21.04`:
```
$ uname -r
5.16.15-arch1-1
$ docker --version
Docker version 20.10.13, build a224086349
```
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal
$ docker --version
Docker version 20.10.7, build 20.10.7-0ubuntu5~20.04.2
```

##### STEPS TO REPRODUCE

Create a base image with from a Dockerfile which sets labels through the `LABEL` instruction.
Run the `docker_container` task twice using this image and the same parameters, with some `labels` set and `comparisons.labels` set to `strict`.

There's an example repo [here](https://github.com/RoGryza/ansible-docker-labels-strict).
Dockerfile:
```
FROM alpine:3.14.4

LABEL foo=bar

CMD sleep infinity
```

playbook:
```yaml
- name: Test strict labels
  hosts: localhost
  connection: local
  tasks:
  - name: Create dummy image
    community.docker.docker_image:
      name: dummy
      build:
        path: .
      source: build
  - name: Run dummy image
    community.docker.docker_container:
      name: dummy
      image: dummy
      state: started
      comparisons:
        labels: strict
      labels:
        dummy: "something"
  - name: Run dummy image again - should be no diff
    community.docker.docker_container:
      name: dummy
      image: dummy
      state: started
      comparisons:
        labels: strict
      labels:
        dummy: "something"
  - name: Cleanup container
    community.docker.docker_container:
      name: dummy 
      state: absent
  - name: Cleanup image
    community.docker.docker_image:
      name: dummy 
      state: absent
```
```
$ ansible-playbook --diff strict_labels.yaml
```

##### EXPECTED RESULTS

The container should not be changed in the second `docker_container` task:
```
PLAY [Test strict labels] *************************************************************************************************************************

...

TASK [Run dummy image again - should be no diff] **************************************************************************************************
ok: [localhost]

...
```

##### ACTUAL RESULTS

```
PLAY [Test strict labels] ******************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [Create dummy image] ******************************************************
changed: [localhost]

TASK [Run dummy image] *********************************************************
--- before
+++ after
@@ -1,4 +1,4 @@
 {
-    "exists": false,
-    "running": false
+    "exists": true,
+    "running": true
 }

changed: [localhost]

TASK [Run dummy image again - should be no diff] *******************************
--- before
+++ after
@@ -1,7 +1,6 @@
 {
     "labels": {
-        "dummy": "something",
-        "foo": "bar"
+        "dummy": "something"
     },
     "running": true
 }

changed: [localhost]

TASK [Cleanup container] *******************************************************
--- before
+++ after
@@ -1,4 +1,4 @@
 {
-    "exists": true,
-    "running": true
+    "exists": false,
+    "running": false
 }

changed: [localhost]

TASK [Cleanup image] ***********************************************************
changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=6    changed=5    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```
