### ISSUE TITLE
Decoding seccomp profile failed with `seccomp:/path/to/custom/seccomp.json`

### ISSUE THREAD

**Issue by didrod** [ansible-collections/community.docker#321]
##### SUMMARY

Decoding seccomp profile failed with `security_opts: ['seccomp:/path/to/seccomp.json']`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`community.docker.docker_container`

##### ANSIBLE VERSION

```paste below
ansible [core 2.12.4]
  config file = /home/inrol/foo/ansible.cfg
  configured module search path = ['/home/inrol/foo/.modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/inrol/foo/.direnv/python-3.10.2/lib/python3.10/site-packages/ansible
  ansible collection location = /home/inrol/foo/.collections
  executable location = /home/inrol/foo/.direnv/python-3.10.2/bin/ansible
  python version = 3.10.2 (main, Mar  3 2022, 14:11:38) [GCC 7.5.0]
  jinja version = 3.1.1
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /home/inrol/foo/.collections/ansible_collections
Collection       Version
---------------- -------
community.docker 2.3.0

# /home/inrol/foo/.direnv/python-3.10.2/lib/python3.10/site-packages/ansible_collections
Collection       Version
---------------- -------
community.docker 2.2.1
```

##### CONFIGURATION

```paste below
COLLECTIONS_PATHS(env: ANSIBLE_COLLECTIONS_PATH) = ['/home/inrol/foo/.collections']
DEFAULT_MODULE_PATH(env: ANSIBLE_LIBRARY) = ['/home/inrol/foo/.modules', '/usr/share/ansible/plugins/modules']
```

##### OS / ENVIRONMENT

Ubuntu 18.04, isolated python environment with `direnv` and `pyenv`.
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

$ docker --version
Docker version 20.10.13, build a224086
```

```
$ python --version
Python 3.10.2

$ pip freeze
ansible==5.5.0
ansible-core==2.12.4
certifi==2021.10.8
cffi==1.15.0
charset-normalizer==2.0.12
cryptography==36.0.2
docker==5.0.3
idna==3.3
Jinja2==3.1.1
MarkupSafe==2.1.1
packaging==21.3
pycparser==2.21
pyparsing==3.0.7
PyYAML==6.0
requests==2.27.1
resolvelib==0.5.4
urllib3==1.26.9
websocket-client==1.3.2
```

##### STEPS TO REPRODUCE

Create the following playbook, then run with `ansible-playbook playbook.yml`.

```yaml
# playbook.yml
---
- name: run container with custom seccomp.json
  hosts: localhost
  tasks:
  - name: download custom seccomp.json
    get_url:
      url: https://raw.githubusercontent.com/moby/moby/master/profiles/seccomp/default.json
      dest: /tmp/seccomp.json
      mode: 0644

  - name: run hello-world
    community.docker.docker_container:
      name: hello-world
      image: hello-world
      state: started
      security_opts:
      - "seccomp:/tmp/seccomp.json"
...
```

##### EXPECTED RESULTS

```
ok: [localhost]
```

##### ACTUAL RESULTS

```paste below
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error starting container 5d1c15587c17b3929fdf64007a30e3f8091f463b28ea55c243454e776be4693b: 500 Server Error for http+docker://localhost/v1.40/containers/5d1c15587c17b3929fdf64007a30e3f8091f463b28ea55c243454e776be4693b/start: Internal Server Error (\"Decoding seccomp profile failed: invalid character '/' looking for beginning of value\")"}
```

Providing `seccomp:unconfined`, the playbook below works fine.
```
# playbook.yml
---
- name: run container with seccomp:unconfined
  hosts: localhost
  tasks:
  - name: run hello-world
    community.docker.docker_container:
      name: hello-world
      image: hello-world
      state: started
      security_opts:
      - "seccomp:unconfined"
...
```

```
$ ansible-playbook playbook.yml
PLAY [run container with seccomp:unconfined] **************************************************************************

TASK [Gathering Facts] ************************************************************************************************
ok: [localhost]

TASK [run hello-world] ************************************************************************************************
changed: [localhost]

PLAY RECAP ************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
