### ISSUE TITLE
[Feature request] Support custom name for docker-compose.yml

### ISSUE THREAD

**Issue by patsevanton** [ansible-collections/community.docker#324]
##### SUMMARY
Please Support custom name for docker-compose.yml

##### COMPONENT NAME
docker_compose 

```yaml
    - name: Create and start services
      community.docker.docker_compose:
        project_src: flask
        docker-compose-name: docker-compose-server.yaml
```
