### ISSUE TITLE
docker build from url of git repository

### ISSUE THREAD

**Issue by paulo-erichsen** [ansible-collections/community.docker#346]
##### SUMMARY

I'd like to ask if `community.docker.docker_image` can be extended to allow `build` param to use a **URL** of a `git `repository.

As noted in the `docker build` documentation [1], users can build an image directly from the command line by passing the URL

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

- `community.docker.docker_image` -> `build` param

##### ADDITIONAL INFORMATION

I'd imagine the configuration could look something like this. Note the `path` and `source` flags.
Source=git doesn't exist currently in the existing ansible-docker, but it would be nice if that was added

```yaml
- name: build docker image for hello-world
  community.docker.docker_image:
    build:
      args:
        path: https://github.com/docker-library/hello-world.git
    name: hello-world-custom
    source: git
```

[1]: https://docs.docker.com/engine/reference/commandline/build/#git-repositories
