### ISSUE TITLE
docker_container: error when image digest used

### ISSUE THREAD

**Issue by kaay-it** [ansible-collections/community.docker#359]
When you parse an image string with digest here:
https://github.com/ansible-collections/community.docker/blob/9c7415e0e71e80cc20714be694fcb4e75f350a52/plugins/modules/docker_container.py#L2981
docker utils doesn't return a tag, but returns image digest:
https://github.com/docker/docker-py/blob/a48a5a9647761406d66e8271f19fab7fa0c5f582/docker/utils/utils.py#L194

Below in code you don't check digest or tag you have gave and use digest as tag in procedure pull_image.
Kindly ask you to provide image digest support in module.

**Comment by kaay-it** [comment]
> Do you mean that `image` is something like `acme/app@sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855`?

Exactly!

**Comment by felixfontein** [comment]
Hmm, I'm not sure that changing our code will have any impact - because `pull()` in Docker SDK for Python does exactly the same thing again: https://github.com/docker/docker-py/blob/a48a5a9647761406d66e8271f19fab7fa0c5f582/docker/api/image.py#L394-L395

But then, I don't see why this is actually wrong, as the API endpoint https://docs.docker.com/engine/api/v1.39/#operation/ImageCreate allows `tag` to contain the digest.

So what exactly is not working for you at the moment? Please give a concrete example.

**Comment by felixfontein** [comment]
I added some tests which should call `pull()` with digests, and they pass: #366

**Comment by kaay-it** [comment]
> I added some tests which should call `pull()` with digests, and they pass: #366

It's strange but I will double check my code and try to change my code accordingly to your test's code......
My playbook code is:
```
    - name: Create and start container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_image }}@{{ image_digest }}"
        env_file: "/app/web.env"
        pull: true
        recreate: true
        restart: true
        published_ports: ["127.0.0.1:{{ service_published_port }}:{{ app_container_port }}"]
        container_default_behavior: compatibility
        state: started
        restart_policy: always
        mounts: "{{ container_mounts }}"
```
and I was got an error:
```
TASK [Create and start container] **********************************************
fatal: [dev-backend]: FAILED! => {"changed": false, "msg": "Error pulling image dockerhub_id/image_name:sha256:d1350f9ca8522ab0dc1afb79595e40870630a125fe086c8d78dd8b923ae5f8f0 - 500 Server Error for http+docker://localhost/v1.41/images/create?tag=sha256%3Ad1350f9ca8522ab0dc1afb79595e40870630a125fe086c8d78dd8b923ae5f8f0&fromImage=dockerhub_id%2Fimage_name: Internal Server Error (\"received unexpected HTTP status: 500 Internal Server Error\")"}
```
docker_image value is
`dockerhub_id/image_name`
image_digest value is
`sha256:d1350f9ca8522ab0dc1afb79595e40870630a125fe086c8d78dd8b923ae5f8f0`
I have no idea what wrong in my code.........
