### ISSUE TITLE
"Load image from archive and push to registry" errors... "image does not exist locally"

### ISSUE THREAD

**Issue by llakssz** [ansible-collections/community.docker#41]
##### SUMMARY

Going by the examples [here](https://docs.ansible.com/ansible/latest/collections/community/general/docker_image_module.html#examples), pushing an image from a .tar file to a private registry is not working.
Ansible complains that the image does not exist locally.
Correct, the image does not exist locally, that's why I'm trying to push the .tar file.
I'm using `source: load`, not `source: local`, so I'm confused as to why my local images are getting checked, so I think this is a bug. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`community.docker.docker_image`?
##### ANSIBLE VERSION

```paste below
ansible 2.9.12
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/myuser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/myuser/.local/lib/python3.6/site-packages/ansible
  executable location = /home/myuser/.local/bin/ansible
  python version = 3.6.9 (default, Oct  8 2020, 12:12:24) [GCC 8.4.0]
```

##### CONFIGURATION

`blank` (`ansible-config dump --only-changed` returns nothing)

##### OS / ENVIRONMENT

Ubuntu 18.04

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  tasks:
  - name: Load image from archive and push to a private registry
    community.docker.docker_image:
      name: registry.int.test/new-image-name
      tag: 1.2.3
      push: yes
      load_path: debian.tar
      source: load
```

tar file was created like:
```
docker pull debian
docker save debian > debian.tar
```

##### EXPECTED RESULTS

I'm not sure of the exact output I should be seeing, but I want the task to not fail! 😀

##### ACTUAL RESULTS

```paste below
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [localhost] ***********************************************************************************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************************************************************************
ok: [localhost]

TASK [Load image from archive and push to a private registry] **************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error pushing image registry.int.test/new-image-name: An image does not exist locally with the tag: registry.int.test/new-image-name"}

PLAY RECAP *****************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

##### Extra
If it's of any use (shows my registry is functional, with the hello-world image etc), this works fine, `hello-world-test.tar` gets created :
``` yaml

- hosts: localhost
  tasks:
  - name: Archive image
    community.docker.docker_image:
      name: registry.int.test/hello-world
      tag: latest
      archive_path: hello-world-test.tar
      source: local
```

**Comment by felixfontein** [comment]
I *think* that loading images only works well when you specify the same name and tag that the image had when being saved. At least that's how `docker save` and `docker load` operate, and the module uses the same API as `docker load`, which - AFAIK - does not allow to query how the image that's loaded is actually called (or maybe one can extract that from the returned log).

I'm not very sure about this though, since I never store or load images to/from tar (or other) files.

**Comment by llakssz** [comment]
Thanks for your reply.

Ok, I tested what you said:
Simply getting the name and version/tag from my tar file:
`docker load -i debian.tar` => `Loaded image: debian:latest`

A new playbook, using the right name and version.
```yaml
- hosts: localhost
  tasks:
  - name: Load image from archive and push to a private registry
    community.docker.docker_image:
      name: registry.int.test/debian
      tag: latest
      push: yes
      load_path: debian.tar
      source: load
```
The output is the same:
`fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error pushing image registry.int.test/debian: An image does not exist locally with the tag: registry.int.test/debian"}`

**Comment by felixfontein** [comment]
That's because `name` must be `debian`. The name of the image is `debian:latest`, not `registry.int.test/debian:latest`, and that's why the module cannot find it after loading. (At least I think so.)

**Comment by llakssz** [comment]
> That's because `name` must be `debian`.

From the docs, `Name format will be one of: name, repository/name, registry_server:port/name.`
I was using option 2: (repository/name).

But ok, using `name` just for the name, and then I still need to put the repository somewhere so I'd use `repository`:
```yaml
- hosts: localhost
  tasks:
  - name: Load image from archive and push to a private registry
    community.docker.docker_image:
      repository: registry.int.test
      name: debian
      tag: latest
      push: yes
      load_path: debian.tar
      source: load
```
This doesn't error out, but it only adds the image to my local docker images. It doesn't get pushed to my registry.

If someone else could have a try, or has any other input, that would be great!

**Comment by llakssz** [comment]
I think I have it, although I still think the implementation/documentation is not perfect. So I think a good idea to keep the issue open.

These are my steps:

Pull down an image, create a tar, and delete the image from our local docker.
(I may have put these steps above, I'm just adding them again for reproducibility!)
```
docker pull alpine:latest
docker save alpine:latest > alpine.tar
docker rmi alpine
```

Then run this playbook:
```yaml
- hosts: localhost
  tasks:
  - name: Load image from archive and push to a private registry
    community.docker.docker_image:
      repository: registry.int.test/alpine
      name: alpine
      tag: latest
      push: yes
      load_path: alpine.tar
      source: load
```
The difference from my previous attempts was that this one includes the image name at the end of the repository value.

This will add the alpine image to our local docker, then tag it with our repository, and finally push the image to the remote registry!

It's important to keep in mind that the image will remain in our local docker install, but we can remove it afterwards if needed:
`docker images`
```
alpine   latest   ...
registry.int.test/alpine   latest   ...
```
