### ISSUE TITLE
Clarification on `inline v2 compose` in documentation

### ISSUE THREAD

**Issue by shantanoo-desai** [ansible-collections/community.docker#469]
##### SUMMARY

For the [`latest` documentation for docker_compose module](https://docs.ansible.com/ansible/latest/collections/community/docker/docker_compose_module.html#id5) there exists an example snippet:

```yaml
- name: Run with inline v2 compose
  hosts: localhost
  gather_facts: false
  tasks:
    - community.docker.docker_compose:
        project_src: flask
        state: absent

    - community.docker.docker_compose:
        project_name: flask
        definition:
          version: '2'
          services:
            db:
              image: postgres
            web:
              build: "{{ playbook_dir }}/flask"
              command: "python manage.py runserver 0.0.0.0:8000"
              volumes:
                - "{{ playbook_dir }}/flask:/code"
              ports:
                - "8000:8000"
              depends_on:
                - db
      register: output

    - ansible.builtin.debug:
        var: output

    - ansible.builtin.assert:
        that:
          - "web.flask_web_1.state.running"
          - "db.flask_db_1.state.running"
```
As a suggestion would it make sense to provide a distinction that the `inline v2 compose` should be `inline v2 specification compose` ? This is in lieu because the example mentions `version: 2` which is pointing towards the Compose Specification V2 and does not mean the docker-compose tool V2.

Initially this causes confusion because the requirements for the module specifically mention `<2.0.0` for docker-compose, however the new docker compose plugin is also often mentioned in the development community as compose v2`.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

Affected Documentation Snippet [`plugins/modules/docker_compose.py`](https://github.com/ansible-collections/community.docker/blob/main/plugins/modules/docker_compose.py#L263)
