### ISSUE TITLE
Monitor status of containers launched with docker-compose

### ISSUE THREAD

**Issue by joaopfg** [ansible-collections/community.docker#475]
##### SUMMARY
I want to monitor the status of containers launched with docker-compose.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
community.docker.docker_compose

##### ADDITIONAL INFORMATION
I want to monitor the status of containers launched with docker-compose. It seems to not be available through the `community.docker.docker_compose` module. My work around for now is to use a bash script like the following:

```bash
#!/bin/bash

DIR="${1}/docker-compose.yml"
RUNNING="$(docker-compose -f $DIR ps --services --filter "status=running")"
SERVICES="$(docker-compose -f $DIR ps --services)"

if [ "$RUNNING" != "$SERVICES" ]; then
    echo "Failed"
    comm -13 <(sort <<<"$RUNNING") <(sort <<<"$SERVICES")
else
    echo "Success"
fi
```

which I execute in the target using the `ansible.builtin.script module`. But this is too slow.

Am I missing something or this kind of task is really not available directly through the `community.docker.docker_compose` module ?

I would expect it to be used like the following:

```yaml
- name: Tasks related to docker-compose
  hosts: targets
  gather_facts: false
  tasks:
    - name: Monitor containers launched with docker-compose
      community.docker.docker_compose:
        project_src: {{ dir }}
        monitor: status
```
