### ISSUE TITLE
docker_container_exec Could not find imported module support code for version. 

### ISSUE THREAD

**Issue by kasir-barati** [ansible-collections/community.docker#477]
##### SUMMARY
I wanted to execute a command inside a container with ansible but it throw an error.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`community.docker.docker_container_exec`

##### ANSIBLE VERSION
```paste below
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/kasir/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
```

##### COLLECTION VERSION
```paste below
```

##### CONFIGURATION
```paste below
```

##### OS / ENVIRONMENT

- target OS version: `Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-100-generic x86_64)`
- local OS version: `Linux kasir 5.15.0-46-generic #49~20.04.1-Ubuntu SMP Thu Aug 4 19:15:44 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

##### STEPS TO REPRODUCE
For me it was just these steps:
- `ansible-galaxy collection install community.docker`
- `ansible-galaxy collection install community.general`
- `pip install docker`

**Important**: I also did this since I  though I do need pip and its docker package in the server too.
```yml
- name: Install general packages which I need in the server
  apt:
    name:
      - tree
      - vim
      - python3
      - python3-pip
    state: present
    update_cache: true
  tags:
    - general-packages
    - tree

- name: install docker pip package
  pip:
    name:
      - docker
    state: present
```

```yaml
- name: Reload the nginx if new config file added or a config file has been changed
  community.docker.docker_container_exec:
    container: "{{ nginx_container_name }}"
    command: nginx -s reload
  # when: copied_nginx_conf_files_task_result.changed
  register: reload_result
```

##### EXPECTED RESULTS
I though this will reload my nginx container but it throw an error

##### ACTUAL RESULTS
Error message:
```
fatal: [SERVER_IP]: FAILED! => {"msg": "Could not find imported module support code for version.  Looked for either StrictVersion.py or version.py"}
```

Any though?
