### ISSUE TITLE
docker-compose: Adds double quotes around single quote, if using "{{variable}}" on a playbook

### ISSUE THREAD

**Issue by linuxmail** [ansible-collections/community.docker#481]
##### SUMMARY

I have an issue with variables and added quotes, which I don't need. I use the docker-compose module to add environment variables with a playbook. For one of them .. I have a JSON string .. with database configuration and password, so I want to have it in a Ansible-vault file. If I run then the playbook .. I get `DATABASES='"{ ....}"'` instead of `DATABASES='{...}'`. The only way to avoid it .. is to add the string direct into the playbook with:
```
...
environment:
                DATABASES: |-
  { .... }
....
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

* community.docker.docker_compose:

##### ANSIBLE VERSION

```
ansible 2.9.27
  config file = /var/lib/rundeck/ansible/ansible_rundeck.cfg
  configured module search path = [u'/var/lib/rundeck/ansible/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]
```

##### COLLECTION VERSION
```
# /home/dfuchs/git/ansible/collections/ansible_collections
Collection       Version
---------------- -------
community.docker 3.1.0  
```

##### OS / ENVIRONMENT

* Debian Buster

##### STEPS TO REPRODUCE
```yaml
---
- name: Manage backoffice container
  hosts: "{{inventory}}"
  gather_facts: no
  vars_files:
    - "{{ inventory_dir }}/group_vars/docker_secrets.yml"
    - "{{ inventory_dir }}/group_vars/container_deploy.yaml"
  tasks:
    - name: "Login into harbor"
      docker_login:
        registry: "{{docker_registry}}"
        username: "{{docker_username}}"
        password: "{{docker_password}}"
    - name: "Create docker-compose file"
      community.docker.docker_compose:
        project_name: backoffice
        remove_orphans: true
        pull: true
        definition:
          version: "3.9"
          services:
            backoffice_nginx:
              image: "{{BACKOFFICE_NGINX_IMAGE}}"
              hostname: localhost
              restart: always
              container_name: backoffice_nginx
              volumes:
                - backoffice-gunicorn_data:/home/app/static/
                - certs:/cert
              networks:
                - app-backoffice
              environment:
                API: backoffice:8000
                NGINX_SSL_PORT: 443
              ports:
                - 9001:443
              depends_on:
                - backoffice_gunicorn
          
            backoffice_gunicorn:
              image: "{{BACKOFFICE_IMAGE}}"
              restart: always
              container_name: backoffice_gunicorn
              hostname: backoffice
              environment:
                DATABASES:  "{{ BACKOFFICE_DATABASES }}"
              volumes:
                - backoffice-gunicorn_data:/app/static/
              networks:
                - app-backoffice
                - config_service_config-service
....
```

* On the Vault file: inventories/test/group_vars/docker_secrets.yml

```
BACKOFFICE_DATABASES: !unsafe |-
 { "default": {}, "users_db": {"ENGINE":"django.db.backends.mysql", "NAME":"backoffice_users", "USER":"user", "PASSWORD":"secret", "HOST":"fra-test-mdb", "PORT":"3306"}, "findb": {"NAME":"financial_db", "ENGINE":"django.db.backends.mysql", "USER":"foo", "PASSWORD":"secret", "HOST":"fra-dev-srv-db.example.local","PORT":"3306"}}
```

##### EXPECTED RESULTS

Same like I use with adding the string direct:

`DATABASES='{ "default": {}, "users_db": {"ENGINE":"django.db.backends.mysql", "NAME":"backoffice_users", "USER":"user", "PASSWORD":"secret", "HOST":"fra-test-mdb", "PORT":"3306"}, "findb": {"NAME":"financial_db", "ENGINE":"django.db.backends.mysql", "USER":"foo", "PASSWORD":"secret", "HOST":"fra-dev-srv-db.example.local","PORT":"3306"}}'`

##### ACTUAL RESULTS
Double quotes around:

`DATABASES="'{ "default": {}, "users_db": {"ENGINE":"django.db.backends.mysql", "NAME":"backoffice_users", "USER":"user", "PASSWORD":"secret", "HOST":"fra-test-mdb", "PORT":"3306"}, "findb": {"NAME":"financial_db", "ENGINE":"django.db.backends.mysql", "USER":"foo", "PASSWORD":"secret", "HOST":"fra-dev-srv-db.example.local","PORT":"3306"}}'"`
