### ISSUE TITLE
docker_container: Temporary failure in name resolution

### ISSUE THREAD

**Issue by serpro69** [ansible-collections/community.docker#482]
##### SUMMARY

Container fails to resolve dns names of internal network

##### ISSUE TYPE

- Bug Report

##### COMPONENT NAME

`docker_container`

##### ANSIBLE VERSION

```
ansible [core 2.13.3]
  config file = ansible.cfg
  configured module search path = ['~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = ~/.virtualenvs/oci/lib/python3.8/site-packages/ansible
  ansible collection location = ~/.ansible/galaxy/collections
  executable location = ~/.virtualenvs/oci/bin/ansible
  python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
  jinja version = 3.0.1
  libyaml = True
```

##### COLLECTION VERSION

```
Collection       Version
---------------- -------
community.docker 2.7.1
```

##### CONFIGURATION

```
ANSIBLE_NOCOWS(env: ANSIBLE_NOCOWS) = True
COLLECTIONS_PATHS(ansible.cfg) = ['~/.ansible/galaxy/collections']
DEFAULT_JINJA2_EXTENSIONSansible.cfg) = jinja2.ext.do
DEFAULT_LOG_PATH(ansible.cfg) = ansible.log
DEFAULT_ROLES_PATH(ansible.cfg) = ['~/.ansible/galaxy/roles']
INTERPRETER_PYTHON(ansible.cfg) = /usr/bin/python3
```

##### OS / ENVIRONMENT

```
# uname -a
Linux rocinante 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

##### STEPS TO REPRODUCE

```
    - docker_container:
        image: liquibase/liquibase:{{ liquibase_version }}
        name: "{{ _liquibase_module }}_liquibase_deploy"
        command:
          - 'update'
          - '--defaultsFile=/liquibase/changelog/liquibase.properties'
          - '--changeLogFile=changelog/{{ liquibase_root_changelog }}'
        volumes:
          - '{{ _liquibase_src }}:/liquibase/changelog:ro'
        working_dir: "{{ playbook_dir }}/../{{ _liquibase_module }}"
        dns_servers:
          - <internal dns server IP>
        #auto_remove: true
        keep_volumes: false
        purge_networks: true
```

##### EXPECTED RESULTS

Container (Liquibase) can resolve dns.

**Note**
Running the same from cli works just fine after adding the custom dns server to `/etc/default/docker`:

```
# cat /etc/default/docker
DOCKER_OPTS="--dns 8.8.8.8 --dns 8.8.4.4 --dns <internal dns server IP>"
```

Docker command:

```
docker run -v /path/to/resources/liquibase:/liquibase/changelog liquibase/liquibase:4.16 --defaultsFile=/liquibase/changelog/liquibase.properties --changeLogFile=changelog/changelog-master.xml update
```

##### ACTUAL RESULTS

Temporary failure in name resolution
