### ISSUE TITLE
Container image name not updated when image registry changes

### ISSUE THREAD

**Issue by ptr727** [ansible-collections/community.docker#485]
##### SUMMARY
I discovered the issue when I change several LSIO containers to pull from `linuxserver/heimdall:latest` to `lscr.io/linuxserver/heimdall:latest`.  
The problem manifested as Watchtower that reported `Unable to update container "/plex": Error: No such image: linuxserver/plex:latest. Proceeding to next.`  
After some [discussions](https://github.com/containrrr/watchtower/discussions/1409#discussioncomment-3874327) with Watchtower I discovered that the problem may have been due to the container not being recreated when the image changed.  

Before I changed `recreate` to `yes`:

```
pieter@server-1:~$ docker container inspect heimdall | jq .[].Config.Image
"linuxserver/heimdall:latest"
pieter@server-1:~$ docker container inspect heimdall | jq .[].Image
"sha256:ee9db55d01f96029523b187a1592c35144f3d26c2f6017a3d9856c7c99e12af5"
pieter@server-1:~$ docker image inspect "sha256:ee9db55d01f96029523b187a1592c35144f3d26c2f6017a3d9856c7c99e12af5" | jq .[].RepoTags
[
  "lscr.io/linuxserver/heimdall:latest"
]
```

After I changed recreate to `yes`:

```
pieter@server-1:~$ docker container inspect heimdall | jq .[].Config.Image
"lscr.io/linuxserver/heimdall:latest"
pieter@server-1:~$ docker container inspect heimdall | jq .[].Image
"sha256:ee9db55d01f96029523b187a1592c35144f3d26c2f6017a3d9856c7c99e12af5"
pieter@server-1:~$ docker image inspect "sha256:ee9db55d01f96029523b187a1592c35144f3d26c2f6017a3d9856c7c99e12af5" | jq .[].RepoTags
[
  "lscr.io/linuxserver/heimdall:latest"
]
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`community.docker.docker_container`

##### ANSIBLE VERSION

```
pieter@server-1:~$ ansible --version
ansible [core 2.13.5]
  config file = None
  configured module search path = ['/home/pieter/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/dist-packages/ansible
  ansible collection location = /home/pieter/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
  jinja version = 3.0.1
  libyaml = True
```

##### COLLECTION VERSION

```
pieter@server-1:~$ ansible-galaxy collection list community.docker

# /home/pieter/.ansible/collections/ansible_collections
Collection       Version
---------------- -------
community.docker 3.1.0

# /usr/local/lib/python3.9/dist-packages/ansible_collections
Collection       Version
---------------- -------
community.docker 2.7.1
```

##### CONFIGURATION

```
pieter@server-1:~$ ansible-config dump --only-changed
```

##### OS / ENVIRONMENT

Proxmox 7.2

##### STEPS TO REPRODUCE

```yaml
- name: "Install Heimdall"
  community.docker.docker_container:
    name: heimdall
    image: lscr.io/linuxserver/heimdall:latest
    pull: yes
    hostname: "heimdall-{{ ansible_hostname }}"
    domainname: "{{ ansible_domain }}"
    restart_policy: unless-stopped
    env:
      TZ: "{{ local_timezone }}"
      PUID: "{{ user_id }}"
      PGID: "{{ group_id }}"
    volumes:
      - "{{ appdata_dir }}/heimdall/config:/config"
    networks:
      - name: "{{ docker_local_network }}"
    # published_ports:
    # External routing via traefik
    # - 80:80
    # - 443:443
    labels:
      traefik.enable: "true"
      traefik.http.routers.heimdall.rule: "Host(`heimdall.{{ ansible_domain }}`)"
      traefik.http.routers.heimdall.entrypoints: "websecure"
      traefik.http.routers.heimdall.priority: "1"
      com.centurylinklabs.watchtower.enable: "true"
    recreate: "{{ docker_container_recreate }}"
```

##### EXPECTED RESULTS

I would like the `recreate: no` logic to be aware of the current and new image name, and either fail the operation when the image changes, or update the image, including updating to the new registry if different.

##### ACTUAL RESULTS

When changing the image registry, the image name does not get updated to reflect the new registry.

```
NA
```
