### ISSUE TITLE
Support pruning all images (`docker image prune --all`)

### ISSUE THREAD

**Issue by georgevarghese185** [ansible-collections/community.docker#499]
##### SUMMARY
Support pruning _all_ unused images

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
community.docker.docker_prune

##### ADDITIONAL INFORMATION
It would be nice if the docker_prune module included a flag to prune _all_ unused images, not just dangling images.

This would be the equivalent of using the `--all`/`-a` option with `docker image prune` ([CLI docs](https://docs.docker.com/engine/reference/commandline/image_prune/#options))

```
docker image prune --all
```

Maybe an `images_all` parameter?

```yaml
- name: Prune all unused images
  community.docker.docker_prune:
    images: true
    images_all: true
```

**Comment by georgevarghese185** [comment]
My apologies. After looking at the [Docker Engine API docs](https://docker-py.readthedocs.io/en/stable/images.html#docker.models.images.ImageCollection.prune) I realized it already supports a `dangling: false` filter to delete all images

And after that I also realized there's a very clear example [in the ansible module documentation](https://docs.ansible.com/ansible/latest/collections/community/docker/docker_prune_module.html#examples) on how to prune ALL images with the `dangling` filter. I somehow overlooked this

```
- name: Prune everything (including non-dangling images)
  community.docker.docker_prune:
    containers: true
    images: true
    images_filters:
      dangling: false
    networks: true
    volumes: true
    builder_cache: true
```

I'll be closing this issue now
