### ISSUE TITLE
How to create a macvlan?

### ISSUE THREAD

**Issue by Svenum** [ansible-collections/community.docker#508]
##### SUMMERY
I want to create a macvlan but I dont understand how it works:

Here is my code:
```yaml
    - name: "Deploy DMZ"
      docker_network:
        name: "DMZ"
        attachable: true
        ipam_config:
            - subnet: "172.16.0.0/24"
            - gateway: "172.16.0.1"
            - iprange: "172.16.0.0/24"
        driver: "macvlan"
        driver_options:
            parent: "eth0"
```

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
docker_network

##### ANSIBLE VERSION
```paste below
ansible [core 2.14.0]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/sven/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /home/sven/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/sbin/ansible
  python version = 3.10.8 (main, Nov  1 2022, 14:18:21) [GCC 12.2.0] (/usr/bin/python)
  jinja version = 3.1.2
  libyaml = True

```

**Comment by Guergeiro** [comment]
I would also like to know this. Docker network doesn't seem to provide this out of the box...

**Comment by felixfontein** [comment]
I have no experience with macvlans, but:

> ```yaml
>         ipam_config:
>             - subnet: "172.16.0.0/24"
>             - gateway: "172.16.0.1"
>             - iprange: "172.16.0.0/24"
> ```

why are you specifing three different IPAM configs here? Shouldn't this be more likely
```yaml
        ipam_config:
            - subnet: "172.16.0.0/24"
              gateway: "172.16.0.1"
              iprange: "172.16.0.0/24"
```
with exactly one config that has all three properties specified?

**Comment by ptr727** [comment]
In case it helps, this is my config, I create bridge and macvlan networks, and then assign IP's in the container configs.

```
# Networks are in lexical order, make sure public is default
# https://github.com/moby/moby/pull/22086
docker_public_network: "aaa_publicnet"
# Bind to specific host network interface
docker_public_network_parent: "vmbr1"
docker_public_network_subnet: "192.168.1.0/24"
docker_public_network_gateway: "192.168.1.1"
docker_local_network: "localnet"
```

```
# Create Docker macvlan Network
- name: "Create Docker macvlan Network"
  community.docker.docker_network:
    name: "{{ docker_public_network }}"
    driver: macvlan
    driver_options:
      parent: "{{ docker_public_network_parent }}"
    ipam_config:
      - subnet: "{{ docker_public_network_subnet }}"
        gateway: "{{ docker_public_network_gateway }}"

# Create Docker bridge Network
- name: "Create Docker bridge Network"
  community.docker.docker_network:
    name: "{{ docker_local_network }}"
    driver: bridge
```

```
- name: "Install Home Assistant"
  community.docker.docker_container:
    name: home-assistant
    image: ghcr.io/home-assistant/home-assistant:latest
    pull: yes
    hostname: home-assistant-direct
    domainname: "{{ ansible_domain }}"
    restart_policy: unless-stopped
    env:
      TZ: "{{ local_timezone }}"
    volumes:
      - "{{ appdata_dir }}/home-assistant/config:/config"
    networks:
      - name: "{{ docker_public_network }}"
        ipv4_address: 192.168.1.26 # home-assistant-direct.home.insanegenius.net
      - name: "{{ docker_local_network }}"
    # published_ports:
    # External routing via traefik, and static IP
    # - 8123:8123
    labels:
      traefik.enable: "true"
      traefik.http.routers.home-assistant.rule: "Host(`home-assistant.{{ ansible_domain }}`) || Host(`home-assistant.{{ external_services_domain }}`)"
      traefik.http.routers.home-assistant.entrypoints: "websecure"
      # Manually specify port and schema
      traefik.http.services.home-assistant.loadbalancer.server.scheme: "http"
      traefik.http.services.home-assistant.loadbalancer.server.port: "8123"
      com.centurylinklabs.watchtower.enable: "true"
    recreate: "{{ docker_container_recreate }}"
```
