### ISSUE TITLE
List Stopped Containers using docker_host_info 

### ISSUE THREAD

**Issue by RedlineTriad** [ansible-collections/community.docker#535]
##### SUMMARY

There is no way I found to get the list of stopped containers.
This should be possible with some kind of module option.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

docker_host_info

##### ADDITIONAL INFORMATION

For my molecule test suite, I want to make sure that no containers crashed, or stopped for any other reasons.
However, when I stopped containers, verification still passed, because stopped containers were not included in the results.

To achieve this I used the following code:

```yaml
---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Get Docker Version
      community.docker.docker_host_info:
        verbose_output: yes
        containers: yes
      register: docker_host_info
      become: true

    - name: Debug
      ansible.builtin.debug:
        var: docker_host_info.containers

    - name: Get List of non-running Containers
      ansible.builtin.set_fact:
        non_running_containers: >-
          {{
            docker_host_info.containers 
            | rejectattr('State', 'eq', 'running')
          }}

    - name: Ensure No Applications are Stopped
      ansible.builtin.assert:
        that: not non_running_containers 
        fail_msg: >-
          Expected all containers to be running, found:
          {{ non_running_containers }}
```
