### ISSUE TITLE
Can't find any examples wher docker_* modules are used together

### ISSUE THREAD

**Issue by cen1** [ansible-collections/community.docker#539]
##### SUMMARY
I can't find any examples in the documentation how to combine modules together. Specifically, 
1. Init swarm
2. Add some labels to each node

While `docker_swarm` runs on the ansible host, `docker_node` by default connects to local docker. `docker_swarm` does not register any cluster information which I could use in `docker_node` so I assume an intermediate task `docker_swarm_info` is needed to get the node list and then iterate over that list. However, `docker_swarm_info` also requires a `docker_host` param to connect to the cluster. I think? using `ansible_host` should do it, but then I also need to have conditionals for manager node.. but I only need to set the labels once so I probably just need a single task that connects on the manager #1 and skip all other hosts..

A simple straightforward example in the docs would be really nice.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
- docker_swarm
- docker_swarm_info
- docker_node

**Comment by cen1** [comment]
This is the best I could come up with.

```
- name: Get list of nodes in Docker Swarm
  docker_swarm_info:
    nodes: true
  register: docker_swarm_info
  when: inventory_hostname in groups['managers'][0]

- name: Add node labels
  docker_node:
    labels_state: replace
    hostname: "{{ item.ID }}"
    labels:
      mykey: mylabel
  loop: "{{ hostvars[groups['managers'][0]]['docker_swarm_info']['nodes'] }}"
  when: inventory_hostname in groups['managers'][0]
```
