### ISSUE TITLE
docker_secret does not hide/redact the password in the output

### ISSUE THREAD

**Issue by NIXKnight** [ansible-collections/community.docker#559]
##### SUMMARY
While creating a docker secret, the docker_secret module does not hide data field in the output when ansible is run with `-vv`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.docker.docker_secret

##### ANSIBLE VERSION
```yaml
ansible-playbook [core 2.14.1]
  config file = /home/saadali/Projects/ansible/ansible-playbooks/ansible.cfg
  configured module search path = ['/home/saadali/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/saadali/Projects/ansible/venv/lib/python3.9/site-packages/ansible
  ansible collection location = /home/saadali/.ansible/collections:/usr/share/ansible/collections
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110] (/home/saadali/Projects/ansible/venv/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```
Collection        Version
----------------- -------
community.general 6.1.0
```

##### CONFIGURATION

```
ANSIBLE_PIPELINING(/home/saadali/Projects/ansible/ansible-playbooks/ansible.cfg) = True
CONFIG_FILE() = /home/saadali/Projects/ansible/ansible-playbooks/ansible.cfg
DEFAULT_MANAGED_STR(/home/saadali/Projects/ansible/ansible-playbooks/ansible.cfg) = This file is auto-generated. Edit at your own risk.
DEFAULT_ROLES_PATH(/home/saadali/Projects/ansible/ansible-playbooks/ansible.cfg) = ['/home/saadali/Projects/ansible/ansible-playbooks/roles', '/home/saadali/Projects/ansible>
DEFAULT_STDOUT_CALLBACK(/home/saadali/Projects/ansible/ansible-playbooks/ansible.cfg) = debug
HOST_KEY_CHECKING(/home/saadali/Projects/ansible/ansible-playbooks/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Debian 11 Bullseye

##### STEPS TO REPRODUCE

Define variables:
```yaml
POSTGRESQL_PASSWORD: "supersecretpassword"
POSTGRESQL_SERVICE_SECRETS:
  - name: "POSTGRESQL_PASSWORD"
    data: "{{ POSTGRESQL_PASSWORD }}"
    data_is_b64: **False**
```

Run a task:
```yaml
- name: Write Docker Swarm Service Secrets
  community.docker.docker_secret:
    name: "{{ item.name }}"
    data: "{{ item.data }}"
    data_is_b64: "{{ item.data_is_b64 }}"
    state: present
  with_items: "{{ DOCKER_SWARM_SERVICE_SECRETS }}"
  when: DOCKER_SWARM_SERVICE_SECRETS is defined and DOCKER_SWARM_SERVICE_SECRETS is iterable
```

##### EXPECTED RESULTS

```
changed: [192.168.1.149] => (item={'name': 'POSTGRESQL_PASSWORD', 'data': '<redacted>', 'data_is_b64': False}) => {
    "ansible_loop_var": "item",
    "changed": true,
    "item": {
        "data": "<redacted>",
        "data_is_b64": false,
        "name": "POSTGRESQL_PASSWORD"
    },
    "secret_id": "l542pgm3yermhqu78xsdl7hb6",
    "secret_name": "POSTGRESQL_PASSWORD"
}
```

##### ACTUAL RESULTS

```
changed: [192.168.1.149] => (item={'name': 'POSTGRESQL_PASSWORD', 'data': 'supersecretpassword', 'data_is_b64': False}) => {
    "ansible_loop_var": "item",
    "changed": true,
    "item": {
        "data": "supersecretpassword",
        "data_is_b64": false,
        "name": "POSTGRESQL_PASSWORD"
    },
    "secret_id": "l542pgm3yermhqu78xsdl7hb6",
    "secret_name": "POSTGRESQL_PASSWORD"
}
```
