### ISSUE TITLE
Failed to import Docker when running docker_container

### ISSUE THREAD

**Issue by 33Fraise33** [ansible-collections/community.docker#57]
##### SUMMARY
When running a module with docker_container I get an error that there is no module named docker

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

docker_container

##### ANSIBLE VERSION

```
ansible 2.10.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/gianni/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.1 (default, Dec 13 2020, 11:55:53) [GCC 10.2.0]

```

##### CONFIGURATION

```paste below
/
```

##### OS / ENVIRONMENT

*Host OS*
```
$ uname -r
5.10.2-2-MANJARO
$ pip install docker                                          
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: docker in /home/gianni/.local/lib/python3.9/site-packages (4.4.1)
Requirement already satisfied: six>=1.4.0 in /usr/lib/python3.9/site-packages (from docker) (1.15.0)
Requirement already satisfied: requests!=2.18.0,>=2.14.2 in /usr/lib/python3.9/site-packages (from docker) (2.25.1)
Requirement already satisfied: websocket-client>=0.32.0 in /usr/lib/python3.9/site-packages (from docker) (0.57.0)
Requirement already satisfied: chardet>=3.0.2 in /usr/lib/python3.9/site-packages (from requests!=2.18.0,>=2.14.2->docker) (3.0.4)
Requirement already satisfied: idna>=2.5 in /usr/lib/python3.9/site-packages (from requests!=2.18.0,>=2.14.2->docker) (2.10)
Requirement already satisfied: urllib3>=1.21.1 in /usr/lib/python3.9/site-packages (from requests!=2.18.0,>=2.14.2->docker) (1.25.10)
$ python --version
Python 3.9.1
```

*Target OS:* 
```
$ uname -r
5.4.85-1-lts
$ docker --version
Docker version 20.10.1, build 831ebeae96
$ python --version
Python 3.9.1
```

##### STEPS TO REPRODUCE

Run latest version of docker and python on the target and run latest version of Ansible, python and python module docker on the host. 

```yaml
- name: setup pihole docker container
  hosts: all
  connection: ssh
  become: true
  roles:
    - pihole

- name: setup pihole docker container
  docker_container:
    name: pihole
    image: pihole/pihole:latest
    networks:
      - name: macvlan333
        ipv4_address: "{{ docker_network.pihole }}"
    purge_networks: yes
    volumes:
      - "/data/pihole/config:/etc/pihole"
      - "/data/pihole/dnsmasq:/etc/dnsmasq.d"
    env:
      TZ: "Europe/Brussels"
      WEBPASSWORD: "{{ pihole_pass }}"
      VIRTUAL_HOST: web.localdomain.lan
      DNS1: 1.1.1.1
      DNS2: 1.0.0.1
    restart: yes
    restart_policy: always
    state: started
    pull: true
    labels:
      traefik.http.routers.pihole.tls: "true"
      traefik.http.routers.pihole.tls.certresolver: "le"
      traefik.http.services.pihole.loadbalancer.server.port: "80"
```

##### EXPECTED RESULTS

Run succeeds

##### ACTUAL RESULTS

Getting an error that docker module is not installed, while it is. Also the output seems to 

```paste below
ansible-playbook -i development pihole.yaml --ask-vault-pass -v
Using /etc/ansible/ansible.cfg as config file
Vault password: 

PLAY [setup pihole docker container] *******************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************************************************************************************************************
Enter passphrase for key '/home/gianni/.keys/gianniKey.pem': 
[WARNING]: Platform linux on host captain is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python interpreter could change the meaning of that path. See
https://docs.ansible.com/ansible/2.10/reference_appendices/interpreter_discovery.html for more information.
ok: [captain]

TASK [setup pihole docker container] *******************************************************************************************************************************************************************************************************
fatal: [captain]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (Docker SDK for Python: docker (Python >= 2.7) or docker-py (Python 2.6)) on captain's Python /usr/bin/python. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter, for example via `pip install docker` or `pip install docker-py` (Python 2.6). The error was: No module named 'docker'"} 
```
