### ISSUE TITLE
services.consensus.deploy.resources.limits value 'pids' does not match any of the regexes: '^x-'

### ISSUE THREAD

**Issue by karolpivo** [ansible-collections/community.docker#595]
##### SUMMARY

community.docker.docker_compose module fails to start service when 'deploy.resources.limits.pids' is defined. The same compose service starts when using the 'docker compose' CLI (Docker Compose version v2.16.0).

Please see docker documentation for reference -> https://docs.docker.com/compose/compose-file/deploy/#resources

Relevant docker compose file section:
```
    deploy:
      resources:
        limits:
          pids: 4096
```
Ansible error message:
`
`fatal: [instance]: FAILED! => {"changed": false, "msg": "Configuration error - The Compose file 'redacted' is invalid because:\nservices.consensus.deploy.resources.limits value 'pids' does not match any of the regexes: '^x-'"}``

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.docker.docker_compose 

##### ANSIBLE VERSION

```paste below
ansible [core 2.14.2]
  config file = None
  configured module search path = ['/home/kp/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/kp/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/kp/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/kp/.local/bin/ansible
  python version = 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below

# /home/kp/.local/lib/python3.10/site-packages/ansible_collections
Collection       Version
---------------- -------
community.docker 3.4.0  

# /home/kp/.ansible/collections/ansible_collections
Collection       Version
---------------- -------
community.docker 3.4.0  
```

##### CONFIGURATION

```paste below
n/a
```

##### OS / ENVIRONMENT

Management Host: Ubuntu 22.04 

Target hosts: tested on Ubuntu 22.04 and Almalinux9

##### STEPS TO REPRODUCE

include below section in a compose file and deploy using Ansible

```
    deploy:
      resources:
        limits:
          pids: 4096
```

```yaml
- name: Start  stack - 
  community.docker.docker_compose:
    project_src: "{{ blockchain_docker_compose_path }}"
    files:
      - dc-execution-{{ clients.execution }}.yml
      - dc-consensus-{{ clients.consensus }}.yml
      - dc-validator-{{ clients.validator }}.yml
    remove_orphans: true
```

##### EXPECTED RESULTS

Compose stack starts. 

##### ACTUAL RESULTS

```paste below
`
`fatal: [instance]: FAILED! => {"changed": false, "msg": "Configuration error - The Compose file 'redacted' is invalid because:\nservices.consensus.deploy.resources.limits value 'pids' does not match any of the regexes: '^x-'"}``

```
