### ISSUE TITLE
docker_compose: How to get the output of 'docker compose up' running a command?

### ISSUE THREAD

**Issue by J7mbo** [ansible-collections/community.docker#596]
When I run `docker-compose up <service> <command>`, I can view the output of the command from the container in terminal.

When I use the `docker_compose` module, it just prints the status as `running` when I debug the output. How can I use this module to retrieve the output of the command once the container has finished running via. docker compose?

```
  tasks:
    - name: "run a command"
      community.docker.docker_compose:
        project_src: ../../
        timeout: 60
        services:
          - terraform
      register: output

    - ansible.builtin.debug:
        var: output
```

This gives me, amongst other stuff:

```
"state": {
    "running": true,
    "status": "running"
}
```

I want to wait for the container to finish running, and then see the output of the command, though. How can I get that?
