### ISSUE TITLE
docker_volume not providing driver options

### ISSUE THREAD

**Issue by wsidl** [ansible-collections/community.docker#603]
##### SUMMARY
I've got a docker swarm that I'm setting up a number of services and need to set up some NFS volumes that I've previously configured using stacks in compose files. The issue is my services don't implement the volumes as expected and behave as if they are typical local volumes (no NFS).

Looking at the Ansible-create volume, they NFS driver options appear as expected, but when I run `docker volumes inspect <name>`, the options are `null`:

```
[
    {
        "CreatedAt": "2023-04-07T19:57:33-07:00",
        "Driver": "local",
        "Labels": {},
        "Mountpoint": "/var/lib/docker/volumes/vol/_data",
        "Name": "vol",
        "Options": null,
        "Scope": "local"
    }
]
```

Creating the volume using a pre-existing stack from a compose file, the volume appears as expected:

```
[
    {
        "CreatedAt": "2022-10-28T15:19:07-07:00",
        "Driver": "local",
        "Labels": {
            "com.docker.stack.namespace": "stack"
        },
        "Mountpoint": "/var/lib/docker/volumes/stack_vol/_data",
        "Name": "stack_vol",
        "Options": {
            "device": ":/volume1/Docker/REDACTED",
            "o": "addr=REDACTED,nolock,soft,rw",
            "type": "nfs4"
        },
        "Scope": "local"
    }
]
```

This is using the following compose config:
```
volumes:
    vol:
        driver: local
        driver_opts:
            type: nfs4
            o: addr=REDACTED,nolock,soft,rw
            device: ":/volume1/Docker/REDACTED"
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

docker_volume

##### ANSIBLE VERSION

```paste below
ansible [core 2.14.4]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/REDACTED/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /REDACTED/HomeDocker/.venv/lib/python3.11/site-packages/ansible
  ansible collection location = /home/REDACTED/.ansible/collections:/usr/share/ansible/collections
  executable location = /REDACTED/HomeDocker/.venv/bin/ansible
  python version = 3.11.2 (main, Feb 26 2023, 12:30:13) [GCC 12.1.1 20220730] (/REDACTED/HomeDocker/.venv/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection       Version
---------------- -------
community.docker 3.4.3
```

##### CONFIGURATION

```
    - name: create volumes
      community.docker.docker_volume:
        name: "{{ item.name }}"
        driver_options:
          type: nfs4
          o: addr=REDACTED,nolock,soft,rw
          device: ":/volume1/Docker/{{ item.dir }}"
      loop:
        - name: vol
          dir: REDACTED
```

##### OS / ENVIRONMENT

- OS: Debian 11
- Swarm: 3 manager nodes

##### STEPS TO REPRODUCE

```yaml

```

##### EXPECTED RESULTS

```
[
    {
        "CreatedAt": "2022-10-28T15:19:07-07:00",
        "Driver": "local",
        "Mountpoint": "/var/lib/docker/volumes/vol/_data",
        "Name": "vol",
        "Options": {
            "device": ":/volume1/Docker/REDACTED",
            "o": "addr=REDACTED,nolock,soft,rw",
            "type": "nfs4"
        },
        "Scope": "local"
    }
]
```

##### ACTUAL RESULTS

```paste below
[
    {
        "CreatedAt": "2023-04-07T19:57:33-07:00",
        "Driver": "local",
        "Labels": {},
        "Mountpoint": "/var/lib/docker/volumes/vol/_data",
        "Name": "vol",
        "Options": null,
        "Scope": "local"
    }
]
```

**Comment by felixfontein** [comment]
> - name: create volumes
>       community.docker.docker_volume:
>         name: "{{ item.name }}"
>         driver_options:
>           type: nfs4
>           o: addr=REDACTED,nolock,soft,rw
>           device: ":/volume1/Docker/{{ item.dir }}"
>       loop:
>         - name: vol
>           dir: REDACTED

You are not specifying the driver, while in your Docker Compose example you do. The Docker Daemon might simply ignore the options if the driver itself isn't provided.

**Comment by wsidl** [comment]
@felixfontein that shouldn't matter in this case since the `driver` property's default value is "local".

Regardless, I tried adding `driver: local` with no success.

**Comment by felixfontein** [comment]
Well, when I run the playbook:
```yml
- hosts: localhost
  tasks:
  - name: create volumes
    community.docker.docker_volume:
      name: vol
      driver: local
      driver_options:
        type: nfs4
        o: addr=http://1.1.1.1,nolock,soft,rw
        device: ":/volume1/Docker/foo"
```
the return value for me is:
```
changed: [localhost] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "api_version": "auto",
            "ca_cert": null,
            "client_cert": null,
            "client_key": null,
            "debug": false,
            "docker_host": "unix://var/run/docker.sock",
            "driver": "local",
            "driver_options": {
                "device": ":/volume1/Docker/foo",
                "o": "addr=http://1.1.1.1,nolock,soft,rw",
                "type": "nfs4"
            },
            "labels": null,
            "name": "vol",
            "recreate": "never",
            "ssl_version": null,
            "state": "present",
            "timeout": 60,
            "tls": false,
            "tls_hostname": null,
            "use_ssh_client": false,
            "validate_certs": false,
            "volume_name": "vol"
        }
    },
    "volume": {
        "CreatedAt": "2023-04-08T21:07:46+02:00",
        "Driver": "local",
        "Labels": null,
        "Mountpoint": "/var/lib/docker/volumes/vol/_data",
        "Name": "vol",
        "Options": {
            "device": ":/volume1/Docker/foo",
            "o": "addr=http://1.1.1.1,nolock,soft,rw",
            "type": "nfs4"
        },
        "Scope": "local"
    }
}
```
(with latest version of community.docker)

**Comment by felixfontein** [comment]
(You didn't provide the version of community.docker BTW, just the one of community.general, so I have no idea which version of community.docker you are using.)

**Comment by wsidl** [comment]
> (You didn't provide the version of community.docker BTW, just the one of community.general, so I have no idea which version of community.docker you are using.)

My bad

**Comment by wsidl** [comment]
I see this too if I run a debug on the registered output. But the issue is when I run `docker volumes inspect vol` from one of the nodes, I get the output with the `Options: null`.

```
user@swarm1:~$ sudo docker volume inspect vol
[
    {
        "CreatedAt": "2023-04-08T12:06:30-07:00",
        "Driver": "local",
        "Labels": {},
        "Mountpoint": "/var/lib/docker/volumes/vol/_data",
        "Name": "vol",
        "Options": null,
        "Scope": "local"
    }
]
```

**Comment by wsidl** [comment]
Also, for consistency in case there's some artefacts causing problems, I've tried removing all cases of the service and volume from all nodes and re-run my playbook with the same results.

**Comment by felixfontein** [comment]
I don't have a Swarm cluster, so I can only run this without Swarm, but for me `docker volume inspect vol` returns
```
[
    {
        "CreatedAt": "2023-04-08T21:54:43+02:00",
        "Driver": "local",
        "Labels": null,
        "Mountpoint": "/var/lib/docker/volumes/vol/_data",
        "Name": "vol",
        "Options": {
            "device": ":/volume1/Docker/foo",
            "o": "addr=http://1.1.1.1,nolock,soft,rw",
            "type": "nfs4"
        },
        "Scope": "local"
    }
]
```
I guess this is a problem with Swarm then. The module is written for plain Docker daemon. It might be that for Swarm, special information needs to be sent that the module that the module isn't doing (and isn't meant to do, because it is for plain Docker, not for Docker Swarm).

**Comment by wsidl** [comment]
Considering the module's writing through the API, the documentation for [Creating Volumes](https://docs.docker.com/engine/api/v1.42/#tag/Volume/operation/VolumeCreate) specifies a `ClusterVolumeSpec` object property must be included. I'm going to make some wild assumptions here but I believe a minimum example that could be used would be

```json
{
    "ClusterVolumeSpec": {
        "AccessMode": {
            "Scope": "multi",
            "Sharing": "all",
            "Availability": "active"
        }
    }
}
```

These values are enums and should be provided as inputs in this module. I may be able to provide a PR to test this theory, just don't expect anything soon.

**Comment by felixfontein** [comment]
The 1.41 API does not accept that value, so the PR must be API version dependent, and also it shouldn't send this information when Docker Daemon is not in Swarm mode.

**Comment by wsidl** [comment]
> The 1.41 API does not accept that value, so the PR must be API version dependent, and also it shouldn't send this information when Docker Daemon is not in Swarm mode.

Very true, but this can be supported.

**Comment by wsidl** [comment]
Ok, after a few hours of playing, discovered two things:
- Docker Swarm Volume management via the API is buggy AF (according to [this post](https://forums.docker.com/t/swarm-nfs-volume-missing-mount-options/134763))
- Setting up volume mounts still works if you deploy the volumes to each node in your swarm.

Although you can't leverage Swarm's orchestration to connect and dismantle mounts as services move between nodes, I managed to workaround the problem with this playbook but loading volumes on all nodes at once. Not suggested practice, but it works for now

```yaml
---
- name: Deploy Cloud Volumes
  hosts: swarm_managers | swarm_workers
  tags:
    - cloud

  tasks:
    - name: create volumes
      community.docker.docker_volume:
        name: "{{ item.name }}"
        driver: local
        driver_options:
          type: nfs4
          o: addr=REDACTED,nolock,soft,rw
          device: ":/volume1/Docker/{{ item.dir }}"
      loop:
        - name: app1
          dir: App1
        - name: app2
          dir: App2

- name: Deploy Cloud Services
  hosts: swarm_managers[0]
  tags:
    - cloud

  tasks:
    name: create App1 service
      community.docker.docker_swarm_service:
        name: app1
        image: fake/app_service
        networks:
          - proxy
        mounts:
          - source: app1
            target: /app
            type: volume
            no_copy: true
```
