### ISSUE TITLE
Offer an include/exclude containers based on a filtering options in the Docker dynamic inventory

### ISSUE THREAD

**Issue by b-enoit-be** [ansible-collections/community.docker#610]
##### SUMMARY
It would be nice to offer the possibility to exclude certain containers from the dynamic inventory, via a white or black list parameter.

For example, in the `amazon.aws.aws_ec2` dynamic inventory, they are proposing two options: 
* [`exclude_filters`](https://docs.ansible.com/ansible/latest/collections/amazon/aws/aws_ec2_inventory.html#parameter-exclude_filters)
* [`include_filters`](https://docs.ansible.com/ansible/latest/collections/amazon/aws/aws_ec2_inventory.html#parameter-include_filters)

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
`community.docker.docker_containers`; `plugins/inventory/docker_containers.py`

##### ADDITIONAL INFORMATION
It would really be nice to have the same kind of feature as the `aws_ec2` dynamic inventory on the Docker one, for example, to exclude; or only include containers with a certain label.

E.g.:
```yaml
plugin: community.docker.docker_containers
docker_host: unix://var/run/docker.sock

include_filters: 
  ## will only include containers having the custom label 'foo' in the inventory
  ## e.g.: In their Dockerfile,`LABEL my_customer_label=foo`
  - docker_config.Labels.my_custom_label:
    - foo 
```
