### ISSUE TITLE
Create secrets or configs from files already on remote

### ISSUE THREAD

**Issue by Zialus** [ansible-collections/community.docker#64]
##### SUMMARY
Would it be possible to create secrets and/or configs from files already on the remote?
This would be specially useful for a GitOps workflow. One would use the git module to clone a repo with all the configs/secrets and use the docker_config/docker_secret module to add them to swarm.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
- community.general.docker_secret
- community.general.docker_config

##### ADDITIONAL INFORMATION
These are the current examples on the documentation

```yml
- name: Create secret foo (from a file on the control machine)
  community.general.docker_secret:
    name: foo
    # If the file is JSON or binary, Ansible might modify it (because
    # it is first decoded and later re-encoded). Base64-encoding the
    # file directly after reading it prevents this to happen.
    data: "{{ lookup('file', '/path/to/secret/file') | b64encode }}"
    data_is_b64: true
    state: present

- name: Create config foo (from a file on the control machine)
  community.general.docker_config:
    name: foo
    # If the file is JSON or binary, Ansible might modify it (because
    # it is first decoded and later re-encoded). Base64-encoding the
    # file directly after reading it prevents this to happen.
    data: "{{ lookup('file', '/path/to/config/file') | b64encode }}"
    data_is_b64: true
    state: present
```

Possibly a new flag could be added to indicate whether the source of the data is the machine running ansible or the target server.
