### ISSUE TITLE
Env file doesn't work in community.docker.docker_compose

### ISSUE THREAD

**Issue by perrfect** [ansible-collections/community.docker#653]
##### SUMMARY
Hello. I use docker-compose.yml for a Weblate project. And all environment variables pass trough env_file:
```
    env_file:
    - ./environment
```
Run my container via ansible:
```
        - name: Run docker-compose
          community.docker.docker_compose:
            project_src: weblate
            env_file: "weblate/environment"
            build: false
            restarted: true
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`weblate/weblate:4.18.1.1`

##### ANSIBLE VERSION
```
ansible [core 2.12.4]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION
```
# /root/.ansible/collections/ansible_collections
Collection       Version
---------------- -------
community.docker 3.4.7  
```

##### STEPS TO REPRODUCE
The docker-compose.yml file looks like:
```
version: '3'
services:
  weblate:
    image: weblate/weblate:4.18.0.1
    ports:
      - 80:8080
    tmpfs:
    - /run
    - /tmp
    volumes:
    - weblate-data:/app/data
    - weblate-cache:/app/cache
    env_file:
    - ./environment
```
And ansilbe playbook looks like:
```
        - name: Run docker-compose
          community.docker.docker_compose:
            project_src: weblate
            env_file: "weblate/environment"
            build: false
            restarted: true
```
##### EXPECTED RESULTS
When I run my ansible playbook docker-compose.yml should write all environment variable from env_file.
