### ISSUE TITLE
allow docker_plugin to upgrade a plugin

### ISSUE THREAD

**Issue by a-gerhard** [ansible-collections/community.docker#659]
##### SUMMARY
It'd be nice if `docker_plugin` was able to upgrade plugins

##### ISSUE TYPE
- New feature for existing module

##### COMPONENT NAME
`docker_plugin`

##### ADDITIONAL INFORMATION
don't really know what to put here. For upgrading, the plugin needs to disable, upgrade, and enable the plugin. I think that specifying something like `state: latest` should check for available upgrades, and apply the upgrade if needed. having a `force` flag might be useful to add the `--force` flag to the disable command.

Alternatively, provide a way to just call `docker upgrade [plugin_name]`, and let the user take care of disabling and enabling it.

**Comment by mindhaq** [comment]
This also applies when an explicit version / tag is used for the `plugin_name`.

I had this in my task:

```yaml
- name: Install and enable loki plugin for docker
  community.docker.docker_plugin:
    alias: loki
    plugin_name: "grafana/loki-docker-driver"
    state: enable
```

and had to change the `plugin_name` to a specific tag `grafana/loki-docker-driver:3.4.2-arm64` because the `latest` tag is not working with arm64 and the plugin was not changed after applying.
