### ISSUE TITLE
Pull the latest images and restart service

### ISSUE THREAD

**Issue by magtimmermans** [ansible-collections/community.docker#662]
##### SUMMARY

I am trying to get the latest image and restart the service with this new image.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

community.docker.docker_compose

##### ANSIBLE VERSION

```
ansible [core 2.14.6]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION

```
# /usr/lib/python3/dist-packages/ansible_collections
Collection       Version
---------------- -------
community.docker 3.4.7  

# /root/.ansible/collections/ansible_collections
Collection       Version
---------------- -------
community.docker 3.4.8 
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```
  tasks:
    - name: rebuild service
      community.docker.docker_compose:
        project_src: /volume1/docker
        services:
            - portainer
        pull: true
        build: true
        nocache: true
        recreate: always
      register: output

```

##### EXPECTED RESULTS

recreated service with latest image

##### ACTUAL RESULTS

no image will be updated and service will be re-created
