### ISSUE TITLE
Inline compose definition and docker-compose logs

### ISSUE THREAD

**Issue by bleetube** [ansible-collections/community.docker#663]
##### SUMMARY

How does one access `docker-compose logs` after using the inline compose feature? I rather liked the elegance of defining the compose contents directly in Ansible, but I'm not sure how to continue using docker-compose after doing this. Sorry if this is already documented somewhere and I missed it in my search.

Do you just use the `/var/lib/docker/containers/*/*-json.log`? If so, any advice for quickly getting a particular container's logs? I figured I can use the container id from `docker ps` to figure out which subdirectory to tab into, but that seems pretty clunky.

For the uninitiated:
```yaml
- name: Start mycontainer with inline definition
  community.docker.docker_compose:
    project_name: mycontainer
    definition:
      version: '3'
      services:
        mycontainer:
          image: ...
```

The docker-compose.yml gets written to /tmp/ansible../docker-compose.yml. Which subsequently vanishes after a reboot.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

* community.docker.docker_compose

##### ANSIBLE VERSION

```paste below
ansible [core 2.15.1]
```
