### ISSUE TITLE
"Compose file is invalid becuase `depends_on` contains unsupported option: 'required'" but works normally when running outside Ansible

### ISSUE THREAD

**Issue by gdfrancia** [ansible-collections/community.docker#676]
##### SUMMARY

I was trying to run a `docker-compose.yml` file using `community.docker.docker_compose`, but I get this error when running it: `"Configuration error - The Compose file '/opt/docker/example/docker-compose.yml' is invalid because:\nservices.backend.depends_on contains unsupported option: 'required'"`. For some reason, when I try running `docker compose up -d` on the machine itself with the same `docker-compose.yml` file, it works fine and it pulls the images and all that. How come that the `docker-compose.yml` file works when running `docker compose` but not when using the `community.docker.docker_compose` module?

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

```
community.docker.docker_compose
```

##### ANSIBLE VERSION

```paste below
ansible [core 2.14.7]
  config file = /home/gdfrancia/src/practice/ansible-error-demo/ansible.cfg
  configured module search path = ['/home/gdfrancia/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /home/gdfrancia/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.4 (main, Jun  7 2023, 00:00:00) [GCC 13.1.1 20230511 (Red Hat 13.1.1-2)] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection       Version
---------------- -------
community.docker 3.4.7
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = /home/gdfrancia/src/practice/ansible-error-demo/ansible.cfg
DEFAULT_HOST_LIST(/home/gdfrancia/src/practice/ansible-error-demo/ansible.cfg) = ['/home/gdfrancia/src/practice/ansible-error-demo/hosts.ini']
HOST_KEY_CHECKING(/home/gdfrancia/src/practice/ansible-error-demo/ansible.cfg) = True
```

##### OS / ENVIRONMENT

Output of `uname -a`:
```
Linux TGT1041 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 GNU/Linux
```

Output of `python3 --version`:
```
Python 3.11.4
```

##### STEPS TO REPRODUCE

1. Make sure that the target machine has `docker` and `docker-compose-plugin` on it.
2. Create an `docker-compose.yml` file. Save it in a folder called `templates` so that ansible will reference that one when running the `ansible.builtin.template` task. 
    
3. Create the ansible playbook that copies the `docker-compose.yml` file into the remote machine.
4. Create a task that runs the `docker-compose.yml` file using `community.docker.docker_compose`.
5. Run the ansible playbook.

Below is an example `docker-compose.yml` file that has an offending line when running with `community.docker.docker_compose`, but not with `docker compose up -d`. Note that this only demos the aforementioned commands to show that it starts up, but the services themselves are not in any way working as intended.
```yaml
# templates/docker-compose.yml
---
version: "3.3"

services:
  backend:
    image: golang:1.20.6-alpine3.18
    restart: always
    depends_on:
      db:
        condition: service_started
        required: true              # offending line that works when running outside ansible
  db:
    image: postgres:15-alpine3.18
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    depends_on:
      db:
        required: true
    ports:
      - 8080:8080
```
```yaml
# run.yml
---
- name: Run Docker Compose
  hosts: all
  become: false
  vars:
    docker_dir: /opt/docker
    project_dir: "{{ docker_dir }}/example"

  tasks:
    - name: Create Project Directory fi not exists
      ansible.builtin.file:
        path: "{{ project_dir }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        state: directory

    - name: Copy `docker-compose.yml` File
      ansible.builtin.template:
        src: templates/docker-compose.yml
        dest: "{{ project_dir }}"

    - name: Run `docker-compose.yml`
      community.docker.docker_compose:
        project_src: "{{ project_dir }}"
        project_name: "example"
        state: present
```

##### EXPECTED RESULTS

It should start the docker compose stack properly without issues.

##### ACTUAL RESULTS

I get the message mentioned above:
```
"msg": "Configuration error - The Compose file '/opt/docker/example/docker-compose.yml' is invalid because:\nservices.backend.depends_on contains unsupported option: 'required'\nservices.adminer.depends_on contains unsupported option: 'required'"
```

```sh
# Run commands:
ansible-playbook run.yml -vvvv --ask-vault-pass
```
Main output in github gist link below:
https://gist.github.com/gdfrancia/d13abf3466eec0ccecc42d3dd9ca4713
