### ISSUE TITLE
Add output_logs to docker_compose

### ISSUE THREAD

**Issue by JohannesFleischer** [ansible-collections/community.docker#678]
##### SUMMARY

When starting a container with `docker-compose` it would be handy to have the option to output the `docker-compose logs` generated. That is for example useful for services, that generate and log information needed to continue (like [hashicorp boundary](https://github.com/hashicorp/boundary))

If the logs could be directly written into a variable, that would be pretty handy, but I guess the easiest way is to just write the logs to the output so that can be registered and searched afterward.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

This feature also does already exist for [docker_container](https://docs.ansible.com/ansible/latest/collections/community/docker/docker_container_module.html#parameters), so the same name could be taken for this option: `output_logs: true|false`

##### ADDITIONAL INFORMATION

```yaml
    - name: Create and start service
      community.docker.docker_compose:
        project_src: boundary
        output_logs: true
      register: output

  - name: Print Boundary credentials
    ansible.builtin.debug: 
      msg: "{{ output | regex_search('.*\bLogin Name\b.*\n.*\bPassword\b.*') }}"
```
