### ISSUE TITLE
Pulling an Docker Image from a local repository fails.

### ISSUE THREAD

**Issue by Someone894** [ansible-collections/community.docker#680]
##### SUMMARY

Pulling an Docker Image from a local repository fails.

##### ISSUE TYPE

- Bug Report

##### COMPONENT NAME

community.docker.docker_image

##### ANSIBLE VERSION

```paste below
AWX 20.1.0
```

##### COLLECTION VERSION

```paste below
3.4.8
```

##### CONFIGURATION

The AWX is running on Kubernetes, so there is no way of getting the `ansible-config`
```paste below

```

##### OS / ENVIRONMENT

The AWX is running on Kubernetes.

##### STEPS TO REPRODUCE

I use this roles with `docker_repository`, `docker_username`, `docker_password` saved under
`defaults/main.yml`

```yaml
---
- name: "Install requirements"
  ansible.builtin.pip:
    name:
      - docker>=4.4.4
- name: "Docker Login"
  community.docker.docker_login:
    registry_url: "{{ docker_repository }}"
    username: "{{ docker_username }}"
    password: "{{ docker_password }}"
- name: "Docker Pull"
   community.docker.docker_image:
     pull: true
     name: "{{ docker_image }}"
     tls_verify: false
- name: "Docker Logout"
  community.docker.docker_login:
    state: absent
    registry_url: "{{ docker_repository }}"
```

And this is my playbook:

```yaml
---
- hosts: server
  vars:
    docker_image: "harbor.local/section/image:latest"
  roles:
    - "docker_pull"
```

##### EXPECTED RESULTS

I expected the docker image to be pulled on the server.

##### ACTUAL RESULTS

I got this error message:

```bash
{
  "module_stdout": "/etc/profile.d/lang.sh: line 19: warning: setlocale: LC_CTYPE: cannot change locale (C.UTF-8)
Traceback (most recent call last):
  File \"/home/caawx/.ansible/tmp/ansible-tmp-1693567228.8018787-59-206371701994884/AnsiballZ_docker_image.py\", line 107, in <module>
    _ansiballz_main()
  File \"/home/caawx/.ansible/tmp/ansible-tmp-1693567228.8018787-59-206371701994884/AnsiballZ_docker_image.py\", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File \"/home/caawx/.ansible/tmp/ansible-tmp-1693567228.8018787-59-206371701994884/AnsiballZ_docker_image.py\", line 48, in invoke_module
    run_name='__main__', alter_sys=True)
  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code
    exec(code, run_globals)
  File \"/tmp/ansible_community.docker.docker_image_payload_5xuu56qu/ansible_community.docker.docker_image_payload.zip/ansible_collections/community/docker/plugins/modules/docker_image.py\", line 1033, in <module>
  File \"/tmp/ansible_community.docker.docker_image_payload_5xuu56qu/ansible_community.docker.docker_image_payload.zip/ansible_collections/community/docker/plugins/modules/docker_image.py\", line 1005, in main
  File \"/tmp/ansible_community.docker.docker_image_payload_5xuu56qu/ansible_community.docker.docker_image_payload.zip/ansible_collections/community/docker/plugins/module_utils/common_api.py\", line 509, in __init__
  File \"/tmp/ansible_community.docker.docker_image_payload_5xuu56qu/ansible_community.docker.docker_image_payload.zip/ansible/module_utils/basic.py\", line 508, in __init__
  File \"/tmp/ansible_community.docker.docker_image_payload_5xuu56qu/ansible_community.docker.docker_image_payload.zip/ansible/module_utils/common/arg_spec.py\", line 268, in validate
  File \"/tmp/ansible_community.docker.docker_image_payload_5xuu56qu/ansible_community.docker.docker_image_payload.zip/ansible/module_utils/common/arg_spec.py\", line 239, in validate
  File \"/tmp/ansible_community.docker.docker_image_payload_5xuu56qu/ansible_community.docker.docker_image_payload.zip/ansible/module_utils/common/parameters.py\", line 733, in _validate_sub_spec
  File \"/tmp/ansible_community.docker.docker_image_payload_5xuu56qu/ansible_community.docker.docker_image_payload.zip/ansible/module_utils/common/parameters.py\", line 809, in set_fallbacks
TypeError: argument of type 'bool' is not iterable
",
  "module_stderr": "Shared connection to svliba01001.wago.local closed.
",
  "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
  "rc": 1,
  "_ansible_no_log": false,
  "changed": false
}
```

A pull via `command` works fine:

```yaml
---
- name: "Install requirements"
  ansible.builtin.pip:
    name:
      - docker>=4.4.4
- name: "Docker Login"
  community.docker.docker_login:
    registry_url: "{{ docker_repository }}"
    username: "{{ docker_username }}"
    password: "{{ docker_password }}"
- name: "Docker Pull"
  command: "docker pull {{ docker_image }}"
- name: "Docker Logout"
  community.docker.docker_login:
    state: absent
    registry_url: "{{ docker_repository }}"
```

**Comment by felixfontein** [comment]
Please check the documentation. `pull` is not a boolean option, but a dictionary. You want `source: pull` instead of `pull: true`.

(The module shouldn't crash, but that's a bug in ansible-core - I'll create a report for that there later on.)

(The `tls_verify` option also likely doesn't do what you think it does - it is for talking to the Docker daemon, *not* for talking to the registry. Since you don't specify it for any other `docker_*` module, you should simply remove it.)

**Comment by Someone894** [comment]
Yes you are right, with this it works perfectly.

```yml
---
- name: "Install requirements"
  ansible.builtin.pip:
    name:
      - docker>=4.4.4
- name: "Docker Login"
  community.docker.docker_login:
    registry_url: "{{ docker_repository }}"
    username: "{{ docker_username }}"
    password: "{{ docker_password }}"
- name: "Docker Pull"
  community.docker.docker_image:
    source: pull
    name: "{{ docker_image }}"
- name: "Docker Logout"
  community.docker.docker_login:
    state: absent
    registry_url: "{{ docker_repository }}"
```

Im sorry for the stupid question, Im farely new to ansible.
