### ISSUE TITLE
docker_compose: fails to load override file containing `!reset`

### ISSUE THREAD

**Issue by benibr** [ansible-collections/community.docker#710]
##### SUMMARY
When using docker-compose with a override file one has to add `!reset` if one wants to unset an already existing value.
See https://docs.docker.com/compose/compose-file/13-merge/
This works as expected with the docker-compose CLI tools but not with Ansible using `community.docker.docker_compose`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.docker.docker_compose

##### ANSIBLE VERSION
```
ansible [core 2.16.0]
  config file = /Users/zsn342/.ansible.cfg
  configured module search path = ['/Users/zsn342/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/zsn342/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.11.6 (main, Oct  2 2023, 13:45:54) [Clang 15.0.0 (clang-1500.0.40.1)] (/opt/homebrew/opt/python@3.11/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION
```
Collection       Version
---------------- -------
community.docker 3.4.11
```

##### OS / ENVIRONMENT
running Ansible on macOS to configure RHEL 9 machines

##### STEPS TO REPRODUCE

use the following files

```yaml
# docker-compose.yml
version: '3.7'

services:
  one:
    profiles:
      - foo
    image: debian
    command: sleep infinity
  two:
    image: debian
    depends_on:
      - one
```

```yaml
# override.yml
version: '3.7'

services:
  two:
    depends_on: !reset []
```

```yaml
# Example play
- hosts: localhost
  tasks:
  - name: Running docker-compose down
    community.docker.docker_compose:
      project_src: "./"
      state: absent
```

and test them with docker-compose:

```
docker compose -f docker-compose.yml -f override.yml --profile two up
```

Then run the ansible playbook.

##### EXPECTED RESULTS

Ansible should start only the "two" Docker container as docker-compose does.

##### ACTUAL RESULTS

The Ansible run fails because it loads the override.yml and cannot parse it cause it's missing the `!reset` constructor.

```
...
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Configuration error - could not determine a constructor for the tag '!reset'\n  in \"override.yml\", line 5, column 17"}
...
```
