### ISSUE TITLE
docker_image fails to load image from local path

### ISSUE THREAD

**Issue by TalLannder** [ansible-collections/community.docker#72]
##### SUMMARY
While using `docker_image` to load an image from local path the step fails with `"msg": "Error loading image image_name - 'NoneType' object is not iterable"`. This step works on ansible v2.9.2 but fails on `2.10.5` installed via pip and on [develop](https://github.com/ansible/ansible/commit/823c72bcb59a5628c0ce21f2145f37f61bae6db9) installed from source.

playbook step:
```
    - name: load image from archive
      docker_image:
        name: "{{app_id}}"
        tag: latest
        push: no
        load_path: "/tmp/{{app_id}}.tar"
        force_source: yes
        force_tag: yes
        source: load
```

Tested on:
```
ansible-playbook 2.10.5
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
```

Note: I'm not sure but maybe the issue related to [PR62](https://github.com/ansible-collections/community.docker/pull/62)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible_collections/community/general/plugins/modules/docker_image.py

##### ANSIBLE VERSION

```
ansible 2.10.5
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
```

##### CONFIGURATION

```
none all default
```

##### OS / ENVIRONMENT

- Control machine: Ubuntu 20.04.1 LTS
- Target node: Ubuntu 18.04.5 LTS

##### STEPS TO REPRODUCE
Build basic image and copy to a local path on target machine and try to load it using docker_image.

```
---
    - name: load image from archive
      docker_image:
        name: my_image
        tag: latest
        push: no
        load_path: "/tmp/my_image.tar"
        force_source: yes
        force_tag: yes
        source: load
```

##### EXPECTED RESULTS
The image loaded to docker on target machine. Works on ansible 2.9.2

##### ACTUAL RESULTS
```
The full traceback is:
  File "/tmp/ansible_docker_image_payload_ke8kfvfh/ansible_docker_image_payload.zip/ansible_collections/community/general/plugins/modules/docker_image.py", line 783, in load_image
fatal: [remote_ip]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "api_version": "auto",
            "archive_path": null,
            "build": null,
            "buildargs": null,
            "ca_cert": null,
            "client_cert": null,
            "client_key": null,
            "container_limits": null,
            "debug": false,
            "docker_host": "unix://var/run/docker.sock",
            "dockerfile": null,
            "force": null,
            "force_absent": false,
            "force_source": true,
            "force_tag": true,
            "http_timeout": null,
            "load_path": "/root/api-accounts-v2.tar",
            "name": "api-accounts-v2",
            "nocache": false,
            "path": null,
            "pull": null,
            "push": false,
            "repository": null,
            "rm": true,
            "source": "load",
            "ssl_version": null,
            "state": "present",
            "tag": "latest",
            "timeout": 60,
            "tls": false,
            "tls_hostname": "localhost",
            "use_tls": null,
            "validate_certs": false
        }
    },
    "msg": "Error loading image image_name - 'NoneType' object is not iterable",
    "stdout": "",
    "stdout_lines": []
}
```
