### ISSUE TITLE
Add labels to Docker images

### ISSUE THREAD

**Issue by SheevaPlug** [ansible-collections/community.docker#726]
##### SUMMARY
Add metadata (labels) to Docker images like "docker build --label <list>".

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
docker.community.docker_image

##### ADDITIONAL INFORMATION
Docker images can have labels to provide additional information for an image, for example to include the exact software version / branch / ... used for that build. The Docker cli can set image labels with the "--label" argument to "docker build". It would not only be an enhancement for some use cases, but also be consistent if docker_image supported this, as other modules in this collection like docker_container, docker_network and docker_volume already do. 

```yaml
- name: Build and push new image
  community.docker.docker_image:
    build:
      path: .
      labels:
        one: 1
        two: 2
    name: "{{ image_name }}"
    tag: "{{ image_tag }}"
    push: true
    source: build
```
