### ISSUE TITLE
Warning message when using docker_compose_v2

### ISSUE THREAD

**Issue by nkn1111** [ansible-collections/community.docker#749]
##### SUMMARY

Getting warning message when given the parameter `pull_policy: always` in the docker-compose.yaml file.

##### ISSUE TYPE
- Warning message handling

##### COMPONENT NAME

docker_compose_v2
##### ANSIBLE VERSION

```paste below
core 2.15.5
```

##### COLLECTION VERSION

```paste below
community.docker  3.6.0-b1
```

##### STEPS TO REPRODUCE

```yaml
version: "2.4"

services:
  some_app:
    image: someapp:1.0.0
    container_name: someapp
    pull_policy: always
```
