### ISSUE TITLE
docker_compose_v2 build functionality

### ISSUE THREAD

**Issue by b-reich** [ansible-collections/community.docker#750]
##### SUMMARY
Add the functionality to build images with docker compose v2

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
docker_compose_v2

##### ADDITIONAL INFORMATION
There are different use-cases for this feature.
- Adding custom configs to an existing image. (e.g. Webserver)
- Build for custom system architecture like arm64
- Directly build from main-branches for testing/development/troubleshooting or not having a image published anywhere. 

Example from v1 module. 
```yaml
- name: Update Reverse Proxy
  community.docker.docker_compose:
  project_src: /opt/reverse-proxy
    pull: true
    build: true
    state: present
```
