### ISSUE TITLE
Support for multiple compose files with docker_compose_v2 module

### ISSUE THREAD

**Issue by goldyfruit** [ansible-collections/community.docker#772]
##### SUMMARY

With `docker_compose`, we had the capability to use multiple `docker-compose.yml` files which is very handy when you want to organise pretty large composition.

```yaml
  community.docker.docker_compose:
    project_src: "{{ _ovos_installer_working_directory }}/{{ _ovos_installer_project_name }}/compose"
    project_name: "{{ _project_name }}"
    files:
      - compose1.yml
      - compose2.yml
      - compose3.yml
    pull: true
    remove_orphans: "{{ ovos_installer_docker_compose_remove_orphans }}"
    remove_images: "{{ ovos_installer_docker_compose_remove_images }}"
    remove_volumes: "{{ ovos_installer_docker_compose_remove_volumes }}"
```

This capability is missing from `docker_compose_v2` but its supported by `docker compose` CLI.

```
  -f, --file stringArray           Compose configuration files
```

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

`docker_compose_v2`

##### ADDITIONAL INFORMATION

https://github.com/ansible-collections/community.docker/pull/739#issuecomment-1902704433
