### ISSUE TITLE
`state: stopped` causes containers to lose volumes, network and other critical info

### ISSUE THREAD

**Issue by binaryfire** [ansible-collections/community.docker#791]
Stopping containers using `state: stopped` seems to mangle the container. Volumes, bind mounts, the restart policy are all stripped from the stopped container, making it impossible to re-start it in the same state.

To reproduce, start a container like this:

```
- name: Create container
  community.docker.docker_container:
    name: my-container
    image: my-image
    state: started
    network_mode: host
    volumes:
      - "{{ app_data_dir }}/.env:/app/.env:ro"
      - "{{ app_data_dir }}/storage:/app/storage"
    restart_policy: on-failure
    restart_retries: 5
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
    env:
      APP_ENV: "{{ 'production' if is_production else 'local' }}"
      MAX_REQUESTS: '1000'
```

Then stop it like this:

```
- name: Stop container
  community.docker.docker_container:
    name: my-container
    state: stopped
```

Then run `docker inspect my-container`. You'll see that the bind mounts, restart policy and network info are gone. If you try and restart the container, it will fail.

Now repeat the container creation task, but instead stop the container using `docker stop my-container`. Then run `docker inspect my-container`. You'll see that all the critical info is still present. And if you try and restart it, it will restart without problems.

**Comment by felixfontein** [comment]
I cannot reproduce this. I am using the playbook
```
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Create container
      community.docker.docker_container:
        name: my-container
        image: alpine:latest
        state: started
        command: /bin/sh -c 'sleep 10m'
        network_mode: host
        volumes:
          - "/path/to/seomthing:/app/:ro"
        restart_policy: on-failure
        restart_retries: 5
        healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
          interval: 30s
          timeout: 5s
          retries: 3
          start_period: 15s
        env:
          APP_ENV: production
          MAX_REQUESTS: '1000'
    - name: Stop container
      community.docker.docker_container:
        name: my-container
        state: stopped
        debug: true
      diff: true
```
Which version of community.docker are you using?

**Comment by binaryfire** [comment]
Hi @felixfontein. This is my version info:

```
ansible [core 2.15.9]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

I've installed via the [Ubuntu PPA](https://launchpad.net/~ansible/+archive/ubuntu/ansible) so whichever version of `community.docker` that comes with that is what I've got.

I'm not sure what more I can do in terms of debugging. When I do this:

```
- name: Stop container
  ansible.builtin.command:
    cmd: "docker stop {{ container_name }}"
```

I can see all the volumes etc. when I inspect the container. And restart it without problems using:

```
- name: Restart container
  community.docker.docker_container:
    name: "{{ container_name }}"
    state: started
```

But when I do this:

```
- name: Stop container
     community.docker.docker_container:
       name: "{{ container_name }}"
       state: stopped
```

I can't see any volumes etc. and it therefore won't start properly. I've switched to using the command for now but obviously it would be great to figure out what's happening

**Comment by binaryfire** [comment]
Actually I'm having problems with `state: started` as well. So if I stop a container using:

```
- name: Stop container
  ansible.builtin.command:
    cmd: "docker stop {{ container_name }}"
```

I'm unable to restart it (volumes etc break) by using:

```
- name: Restart container
  community.docker.docker_container:
    name: "{{ container_name }}"
    state: started
```

But I can restart it using:

```
- name: Restart container
  ansible.builtin.command:
    cmd: "docker start{{ container_name }}"
```

My Docker version is `25.0.2, build 29cf629` in case that helps. I'll try and create a reproduction repo as well.
