### ISSUE TITLE
[docker_swarm] enable easy way to add all hosts as workers to existing Docker Swarm

### ISSUE THREAD

**Issue by bluepuma77** [ansible-collections/community.docker#795]
##### SUMMARY
Enable easy way to add all hosts as workers to existing Docker Swarm

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
docker_swarm 

##### ADDITIONAL INFORMATION
I can initialise a Docker Swarm with filtering all hosts for tag `swarm_manager=true`:
```
# hosts.ini
[all]
srv1 ansible_host=1.2.3.4 ansible_user=root swarm_manager=true
srv2 ansible_host=1.2.3.5 ansible_user=root
srv3 ansible_host=1.2.3.6 ansible_user=root swarm_manager=true
srv4 ansible_host=1.2.3.7 ansible_user=root
srv5 ansible_host=1.2.3.8 ansible_user=root swarm_manager=true
srv6 ansible_host=1.2.3.9 ansible_user=root
```

```
- hosts: all
  gather_facts: true

  tasks:
    - name: Init a new Docker Swarm on managers
      community.docker.docker_swarm:
        state: present
      when: hostvars[inventory_hostname]['swarm_manager'] | default(false) == "true"
```
How can I easily join the other hosts to the existing Docker Swarm as simple workers? 

Is this a missing feature or just missing as an example?

`state: present` means `manager` and `state: join` means `worker`?

How to retrieve the join data from the manager nodes when iterating over worker nodes?

**Comment by niraami** [comment]
As far as I can tell, `present` is always `init` and `join` works for both managers and workers, just has to be the right token type.

The most concise way of doing this that I found is this:
```yaml
- name: Initialize swarm
  community.docker.docker_swarm:
    state: present
  register: swarm_status
  when: inventory_hostname in groups['managers'][0]

- name: Connect to Docker Swarm as a Manager
  community.docker.docker_swarm:
    state: join
    timeout: 60
    join_token: "{{ hostvars[groups['managers'][0]].swarm_status['swarm_facts']['JoinTokens']['Manager']}}"
    remote_addrs: "{{ hostvars[groups['managers'][0]]['ansible_default_ipv4']['address'] }}:2377"
  when: inventory_hostname in groups['managers'] and inventory_hostname not in groups['managers'][0]

- name: Connect to Docker Swarm as a Worker
  community.docker.docker_swarm:
    state: join
    timeout: 60
    join_token: "{{ hostvars[groups['managers'][0]].swarm_status['swarm_facts']['JoinTokens']['Worker'] }}"
    remote_addrs: "{{ hostvars[groups['managers'][0]]['ansible_default_ipv4']['address'] }}:2377"
  when: inventory_hostname in groups['workers']
```

With the inventory being structured like this:
```yaml
all:
  children:
    managers:
      hosts:
        host-1
        host-2
    workers:
      hosts:
        host-3
        host-4
```
