### ISSUE TITLE
Permission denied on setting docker_login for a user other than root using config_path

### ISSUE THREAD

**Issue by ieugen** [ansible-collections/community.docker#81]
Hi,

So this might be a feature request instead of a bug. 

##### SUMMARY

I believe docker_login should allow you to set user/group for the created config file or to use "docker" group instead of root.
This is important when setting up configuration for another user.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`community.docker.docker_login`

##### ANSIBLE VERSION

```paste below
ansible 2.9.16
  config file = REDACTED
  configured module search path = ['REDACTED']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.1+ (default, Jan 20 2021, 14:49:22) [GCC 10.2.1 20210110]

```

##### CONFIGURATION

Not relevant.

##### OS / ENVIRONMENT

Not relevant. Debian host and Ubuntu as target.

##### STEPS TO REPRODUCE

I've tried to use docker_login to setup credentials for a user other than root.

```yaml
- name: Log into registry for ubuntu user
  community.docker.docker_login:
    registry_url: REDACTED
    config_path: /home/ubuntu/.docker/config.json
    username: REDACTED
    password: REDACTED
```

##### EXPECTED RESULTS

I would like to push/pull images from the host I created the authentication for.

##### ACTUAL RESULTS

I can't pull images:

```
 docker pull REDACTED/nginx
WARNING: Error loading config file: /home/ubuntu/.docker/config.json: open /home/ubuntu/.docker/config.json: permission denied
Using default tag: latest
Error response from daemon: Head https://REDACTED/v2/nginx/manifests/latest: no basic auth credentials
```

The permissions are set so that only root can access the file.
```
ls -la ~/.docker/config.json 
-rw------- 1 root root 236 Feb  7 09:11 /home/ubuntu/.docker/config.json
```

**Comment by felixfontein** [comment]
The module currently works for the current user. Have you tried running something like
```
- name: Log into registry for ubuntu user
  community.docker.docker_login:
    registry_url: REDACTED
    username: REDACTED
    password: REDACTED
  become_user: ubuntu
  become: true
```
instead?

Also, having a `docker` group/user is something that is not universal, and in general it would be a really bad idea to automatically make all `.docker/config.json` files to be readable by all users in the `docker` group.

I guess what we could do is allow to set user/group and even permissions for the config file, similar to how the `file` module works. But that would definitely be a feature, not a bugfix.

**Comment by ieugen** [comment]
Hi @felixfontein,

Thanks for the feedback.

I have this in hosts:
```
[all:vars]
ansible_become=true
ansible_python_interpreter=/usr/bin/python3
ansible_user=ubuntu
```

So I guess the only option is to add the properties to allow for file configuration.

Right now I use this workaround, but it's an extra task and depending on how many hosts you have, it might slow things down.

```
- name: Set proper permissions for /home/ubuntu/.docker/config.json until https://github.com/ansible-collections/community.docker/issues/81
  ansible.builtin.file:
    path: /home/ubuntu/.docker/config.json
    state: file
    group: ubuntu
    owner: ubuntu
```
