### ISSUE TITLE
Idempotence test failure on the `docker_compose_v2_pull`

### ISSUE THREAD

**Issue by DeadNews** [ansible-collections/community.docker#813]
##### SUMMARY

When running `molecule test`, the idempotence test fails on the task `docker_compose_v2_pull`.

##### ISSUE TYPE

- Bug Report

##### COMPONENT NAME

`community.docker.docker_compose_v2_pull`

##### ANSIBLE VERSION

```console
$ ansible --version

ansible [core 2.16.3]
  config file = /home/deadnews/git/deadnews-template-ansible/ansible.cfg
  configured module search path = ['/home/deadnews/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/deadnews/.cache/pypoetry/virtualenvs/deadnews-template-ansible-EQAYLr04-py3.12/lib/python3.12/site-packages/ansible
  ansible collection location = /home/deadnews/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/deadnews/.cache/pypoetry/virtualenvs/deadnews-template-ansible-EQAYLr04-py3.12/bin/ansible
  python version = 3.12.2 (main, Feb 25 2024, 21:08:02) [GCC 13.2.1 20230801] (/home/deadnews/.cache/pypoetry/virtualenvs/deadnews-template-ansible-EQAYLr04-py3.12/bin/python)
  jinja version = 3.1.3
  libyaml = True
```

##### COLLECTION VERSION

```console
$ ansible-galaxy collection list community.docker

# /home/deadnews/.ansible/collections/ansible_collections
Collection       Version
---------------- -------
community.docker 3.8.0
```

##### STEPS TO REPRODUCE

```yaml
- name: Pull a Docker compose project
  community.docker.docker_compose_v2_pull:
    project_src: /path/to/project
```

```console
$ molecule test --all

CRITICAL Idempotence test failed because of the following tasks:
*  => docker_compose_v2_pull : Pull a Docker compose project
```

**Comment by felixfontein** [comment]
Which Docker Compose version are you using? Also what's the stderr output of the supposedly idempotent run?

**Comment by DeadNews** [comment]
>Which Docker Compose version are you using?

Latest version from `https://download.docker.com/linux/{{ ansible_distribution | lower }}`.

>Also what's the stderr output of the supposedly idempotent run?

`molecule --debug test` does not provide this information.

**Comment by DeadNews** [comment]
>Which Docker Compose version are you using?

The latest version. Currently `v2.24.7`.

>Also what's the stderr output of the supposedly idempotent run?

Play:

```yml
- name: Pull images for Docker Compose project
  community.docker.docker_compose_v2_pull:
    project_src: /path/to/project
  register: pull_output

- name: Show pull results
  ansible.builtin.debug:
    var: pull_output

- name: Pull images for Docker Compose project [2 pass]
  community.docker.docker_compose_v2_pull:
    project_src: /path/to/project
  register: pull_output_2

- name: Show pull results [2 pass]
  ansible.builtin.debug:
    var: pull_output_2
```

`docker-compose.yml` example:

```yml
version: "3"
services:
  web:
    image: ghcr.io/deadnews/deadnews-template-go:2.0.3@sha256:2d66ff9a4d36b3682b2f94ec7a575d3d2e6744ac678ecfc2b82b58200aa6f845
````

Output:

```json
    "pull_output": {
        "actions": [
            {
                "id": "web",
                "status": "Pulling",
                "what": "service"
            }
        ],
        "changed": true,
        "failed": false,
        "stderr": " web Pulling \n web Pulled \n",
        "stderr_lines": [
            " web Pulling ",
            " web Pulled "
        ]
    }
```

```json
    "pull_output_2": {
        "actions": [
            {
                "id": "web",
                "status": "Pulling",
                "what": "service"
            }
        ],
        "changed": true,
        "failed": false,
        "stderr": " web Pulling \n web Pulled \n",
        "stderr_lines": [
            " web Pulling ",
            " web Pulled "
        ]
    }
```
