### ISSUE TITLE
.Env file not found - command executed in wrong folder

### ISSUE THREAD

**Issue by Tree4Free** [ansible-collections/community.docker#827]
##### SUMMARY

The docker compose action fails with the following message:
```
"env file /home/xyz/app/app/environment.env not found: stat /home/xyz/app/app/environment.env: no such file or directory"
```

This is roughly the roles I run:
```
- name: Create source directory
  file:
    path: "{{ target_folder }}"
    state: directory

- name: Copy docker-compose file
  copy:
    src: "{{ playbook_dir }}/files/{{ env_type }}/{{ app_type }}/docker-compose.yaml"
    dest: "{{ target_folder }}/docker-compose.yaml"

- name: Copy env file
  copy:
    src: "{{ playbook_dir }}/files/{{ env_type }}/{{ app_type }}/environment.env"
    dest: "{{ target_folder }}/environment.env"

- name: Restart Container
  community.docker.docker_compose_v2:
    project_src: "{{ target_folder }}"
    pull: always
  tags:
    - restart
```

My docker compose file that is copied in the second step looks like this:
```
services:
  app:
    image: private-image
    ports:
      - "8083:8083"
      - "9999:9999"
    env_file:
      - environment.env
    restart: unless-stopped
```

So for what ever reason it runs the command
```
/usr/bin/docker --host unix:///var/run/docker.sock compose --ansi never --progress plain --project-directory app ps --format json --all --no-trunc
```
inside `/home/xyz/app` (`{{target_folder}}`) instead of in the home directory of user xyz.

Until this week I used the v1 version of the docker_compose role and this setup worked fine however after doing an apt update on the targets it stopped working and I had to upgrade to the v2 version so maybe I missed something when upgrading.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

community.docker.docker_compose_v2

##### ANSIBLE VERSION

```paste below
ansible [core 2.12.10]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/xyz/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/xyz/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
  jinja version = 2.11.3
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /home/xyz/.ansible/collections/ansible_collections
Collection       Version
---------------- -------
community.docker 3.8.1

# /usr/lib/python3/dist-packages/ansible_collections
Collection       Version
---------------- -------
community.docker 2.6.0
```

##### OS / ENVIRONMENT

Debian 11.9

##### EXPECTED RESULTS

The deployment of the compose stack works.

##### ACTUAL RESULTS

I get an error when running the ansible command.
