### ISSUE TITLE
Feature Request: compose_v2 inline definition

### ISSUE THREAD

**Issue by TheOneValen** [ansible-collections/community.docker#829]
##### SUMMARY
Please allow an inline definition of the compose content instead of using a project_src like with V1.

##### ISSUE TYPE
- Feature as in V1

##### COMPONENT NAME

- Same as V1?

##### ADDITIONAL INFORMATION

for example:

```yaml

    - name: Start flask project with inline definition
      community.docker.docker_compose_v2:
        project_name: flask
        definition:
          version: '2'
          services:
            db:
              image: postgres
            web:
              build: "{{ playbook_dir }}/flask"
              command: "python manage.py runserver 0.0.0.0:8000"
              volumes:
                - "{{ playbook_dir }}/flask:/code"
              ports:
                - "8000:8000"
              depends_on:
                - db
      register: output
```
