### ISSUE TITLE
User parameter in docker_container module is not working

### ISSUE THREAD

**Issue by MarcOrfilaCarreras** [ansible-collections/community.docker#840]
##### SUMMARY

When using the community.docker.docker_container Ansible module to deploy a Docker container and specifying the user parameter to set the user and group inside the container, the parameter appears to be ignored. As a result, the container runs with the default user and group, causing permission issues when accessing files or directories mounted into the container.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

community.docker.docker_container

##### ANSIBLE VERSION

```paste below
2.14.4
```

##### COLLECTION VERSION

```paste below
# /home/<redacted>/.ansible/collections/ansible_collections
Collection       Version
---------------- -------
community.docker 3.9.0  

# /usr/lib/python3/dist-packages/ansible_collections
Collection       Version
---------------- -------
community.docker 1.2.2 
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = None
```

##### OS / ENVIRONMENT

Target: Raspberry Pi OS (6.6.20+rpt-rpi-v8)
Client: Ubuntu 22.04

##### STEPS TO REPRODUCE

```yaml
---
- name: Creates Files directory
  ansible.builtin.file:
    path: /opt/docker/vikunja/files
    state: directory

- name: Creates DB directory
  ansible.builtin.file:
    path: /opt/docker/vikunja/db
    state: directory

- name: Create vikunja.db file
  ansible.builtin.file:
    path: /opt/docker/vikunja/db/vikunja.db
    state: touch
    owner: "0"
    group: "0"
    mode: "0644"

- name: Deploy Vikunja
  community.docker.docker_container:
    name: vikunja
    recreate: yes
    image: vikunja/vikunja:latest
    user: "0:0"
    ports:
      - "127.0.0.1:9009:3456"
    env:
      VIKUNJA_SERVICE_JWTSECRET: "{{ vikunja_jwt_token }}"
      VIKUNJA_SERVICE_PUBLICURL: https://vikunja.{{ caddy_domain }}
      VIKUNJA_DATABASE_PATH: /db/vikunja.db
      VIKUNJA_SERVICE_ENABLEREGISTRATION: "false"
    volumes:
      - /opt/docker/vikunja/files:/app/vikunja/files
      - /opt/docker/vikunja/db:/db
    labels:
      flame.type: "application"
      flame.name: "Vikunja"
      flame.url: "https://vikunja.{{ caddy_domain }}"
      com.centurylinklabs.watchtower.enable: "true"
    restart_policy: always
```

##### EXPECTED RESULTS

When specifying the user parameter in the community.docker.docker_container Ansible module, the container should run with the user and group ID (UID:GID) provided, ensuring that files and directories mounted into the container inherit the correct permissions. This behavior ensures that the container operates with the expected user privileges, preventing permission issues and ensuring the security and stability of deployments.

##### ACTUAL RESULTS

Despite specifying the user parameter in the community.docker.docker_container Ansible module, the container runs with the default user and group, ignoring the provided UID and GID. This results in permission issues when accessing files or directories mounted into the container, as they inherit the incorrect permissions.
