### ISSUE TITLE
Support pruning all builder image (docker builder prune --all)

### ISSUE THREAD

**Issue by Korhm** [ansible-collections/community.docker#844]
##### SUMMARY
Support of `--all` for builder_cache (Remove all unused build cache, not just dangling ones)

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
community.docker.docker_prune

##### ADDITIONAL INFORMATION
I would like to use this component to prune all builder cache, like the `--all` option in [docker builder prune](https://docs.docker.com/reference/cli/docker/builder/prune/#options)

```yaml
- name: "Remove builder cache"
  community.docker.docker_prune:
    builder_cache: true
    builder_cache_all: true
  register: result
```
