### ISSUE TITLE
How to use `files`? 

### ISSUE THREAD

**Issue by mihalt** [ansible-collections/community.docker#849]
I haven't found in docs how to use [files](https://docs.ansible.com/ansible/latest/collections/community/docker/docker_compose_module.html#parameter-files). I try something like
```
User
  tasks:
    community.docker.docker_compose:
      files:
        - "./mycustom-compose.yml"
```

And get an error like:
 ERROR! A malformed block was encountered while loading tasks: {'community.docker.docker_compose': {'files': ['./mycustom-compose.yml']}} should be a list or None but is <class 'ansible.parsing.yaml.objects.AnsibleMapping'>

**Comment by felixfontein** [comment]
1. I would suggest to not use the `docker_compose` module, since it is now deprecated, and use `docker_compose_v2` instead.

2. The problem has nothing to do with `files`, but that your file above is not anything that ansible itself can parse. Tasks should be a **list** of tasks, not a dictionary of tasks. If you need more help with this, better ask on the Ansible community forum (https://forum.ansible.com/).

**Comment by mihalt** [comment]
> 1. I would suggest to not use the `docker_compose` module, since it is now deprecated, and use `docker_compose_v2` instead.
> 
>     2. The problem has nothing to do with `files`, but that your file above is not anything that ansible itself can parse. Tasks should be a **list** of tasks, not a dictionary of tasks. If you need more help with this, better ask on the Ansible community forum (https://forum.ansible.com/).

wow, ahaha, you are righ! 

so, I use like this now
```
  tasks:
    - community.docker.docker_compose_v2:
        files:
          - "./mycustom-compose.yml"
```
