### ISSUE TITLE
Pass envs to docker-compose

### ISSUE THREAD

**Issue by mihalt** [ansible-collections/community.docker#850]
I am tryting to pass envs to use it like

```
services:
  rabbit:
    restart: always
    image: rabbitmq
    volumes:
      - ${DATABASES_FOLDER}/rabbit:/var/lib/rabbitmq
```

I did standard [environment attribute](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_environment.html#setting-the-remote-environment-in-a-task), but it doesn't work for me. They don't pass to my docker compose file that I use in ansible like

```
  environment:
    DATABASES_FOLDER: /
  tasks:
    - ansible.builtin.copy:
        src: ./docker-compose.yml
        dest: .
    - community.docker.docker_compose_v2:
        project_src: "."
```

I haven't found anything except [env_files](https://docs.ansible.com/ansible/latest/collections/community/docker/docker_compose_v2_module.html#parameter-env_files) attribute in your docs. I think the passing environments like docker compose run -e VAR should help.

**Comment by felixfontein** [comment]
`environment` sets environment variables while running modules, so this is equivalent to `DATABASES_FOLDER=/ docker compose run ...`.

Right now there is no way to pass `--env` to `docker compose`, neither with the old nor with the new Docker compose module.

**Comment by veerendra2** [comment]
Hello, I'm able to use `environment` like in below

`playbook.yaml`
```yaml
...
    - name: Docker Compose UP
      community.docker.docker_compose_v2:
        project_src: "/path/compose/project"
        recreate: always
        files:
          - compose.production.yml
      environment: "{{ env_vars }}"
...
```
`vars.yaml`
```yaml
env_vars:
  - MY_DOMAIN: "mydomain.duckdns.org"
  - MY_PROVIDER: "duckdns"
  - PUID: "{{ ansible_facts.user_uid }}"
  - PGID: "{{ ansible_facts.user_gid }}"
```
