### ISSUE TITLE
Failure to pull with docker_compose_v2 despite authenticating previously

### ISSUE THREAD

**Issue by milongo** [ansible-collections/community.docker#851]
##### SUMMARY

Pulling from private registry doesn't work after doing docker login

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`community.docker.docker_login` and `community.docker.docker_compose_v2` / `community.docker.docker_compose_v2_pull module`
##### ANSIBLE VERSION

```paste below
ansible [core 2.16.6]
  config file = /Users/milongo/LocalDocs/horoma/devops-iac-automation/ansible.cfg
  configured module search path = ['/Users/milongo/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/milongo/miniconda3/envs/devops-iac/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/milongo/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/milongo/miniconda3/envs/devops-iac/bin/ansible
  python version = 3.10.14 (main, Mar 21 2024, 11:21:31) [Clang 14.0.6 ] (/Users/milongo/miniconda3/envs/devops-iac/bin/python3.10)
  jinja version = 3.1.3
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /Users/milongo/miniconda3/envs/devops-iac/lib/python3.10/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 8.6.0 
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = /Users/milongo/LocalDocs/horoma/devops-iac-automation/ansible.cfg
EDITOR(env: EDITOR) = nano
PAGER(env: PAGER) = less
```

##### STEPS TO REPRODUCE

```yaml
- name: Run docker pipeline
  hosts: "{{ target }}"
  vars:
    registry_url: "{{ ecr_registry_url }}"
  tasks:
    - name: Get ansible user data
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        state: present
      register: user_details
    
    - name: Docker login to AWS ECR
      community.docker.docker_login:
        state: present
        username: "AWS" # change this depending on private repository
        password: "{{ ecr_login_password }}"
        registry_url: "{{ registry_url }}"
      changed_when: true

    - name: Docker compose repo
      community.docker.docker_compose_v2:
        project_src: "{{ user_details.home }}/{{ path_to_repos }}/repo"
        state: "present"
```

##### EXPECTED RESULTS

After logging in, successfully being able to pull my images in private repository.

##### ACTUAL RESULTS

Failure to authenticate

```paste below
fatal: [18.208.187.13]: FAILED! => {"actions": [{"id": "my-image", "status": "Pulling", "what": "service"}], "changed": false, "cmd": "/snap/bin/docker compose --ansi never --progress plain --project-directory /home/ubuntu/docker/my-image up --detach --no-color --quiet-pull --", "containers": [], "images": [], "msg": "Error when processing my-image: Error response from daemon: Head \"[https://account-id.dkr.ecr.region.amazonaws.com/v2/my-image/manifests/latest\](https://account-id.dkr.ecr.region.amazonaws.com/v2/my-image/manifests/latest%5C)": no basic auth credentials", "rc": 18, "stderr": " my-image Pulling \n my-image Error \nError response from daemon: Head \"[https://account-id.dkr.ecr.region.amazonaws.com/v2/my-image/manifests/latest\](https://account-id.dkr.ecr.region.amazonaws.com/v2/my-image/manifests/latest%5C)": no basic auth credentials\n", "stderr_lines": [" my-image Pulling ", " my-image Error ", "Error response from daemon: Head \"[https://account-id.dkr.ecr.region.amazonaws.com/v2/my-image/manifests/latest\](https://account-id.dkr.ecr.region.amazonaws.com/v2/my-image/manifests/latest%5C)": no basic auth credentials"], "stdout": "", "stdout_lines": []}
```
