### ISSUE TITLE
community.docker.docker_host_info : Error connecting: Error while fetching server API version: Not supported URL scheme http+docker

### ISSUE THREAD

**Issue by D0wn3r** [ansible-collections/community.docker#868]
##### SUMMARY

I'm trying to get docker info through Ansible with the module `community.docker.docker_host_info` but it doesn't work anymore.
It's on a fresh install (fresh ubuntu 22.04 with docker 26.0.X and also tried with 25.0.4)

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible [core 2.15.4]
  config file = /home/simco-dev/PROJECTS/pca/ansible.cfg
  configured module search path = ['/home/simco-dev/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/dist-packages/ansible
  ansible collection location = /home/simco-dev/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.14 (main, Apr  6 2024, 18:45:05) [GCC 9.4.0] (/usr/bin/python3.10)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /usr/local/lib/python3.10/dist-packages/ansible_collections
Collection        Version
----------------- -------
community.general 7.4.0

# <home_path>/.ansible/collections/ansible_collections
Collection       Version
---------------- -------
community.docker 3.10.2
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = <path>/ansible.cfg
DEFAULT_ROLES_PATH(<path>/ansible.cfg) = ['<path>/ansible-common-roles']
HOST_KEY_CHECKING(<path>/ansible.cfg) = False
PAGER(env: PAGER) = less
```

##### OS / ENVIRONMENT

Fresh instance ubuntu 22.04 from the cloud provider Scaleway

##### STEPS TO REPRODUCE

with docker_version: "5:25.0.4-1~ubuntu.20.04~focal"

```yaml
---
- name: Install required system packages
  ansible.builtin.apt:
      pkg:
          - ca-certificates=20230311ubuntu0.22.04.1
          - curl=7.81.0-1ubuntu1.16
          - python3-pip=22.0.2+dfsg-1ubuntu0.4
          - gnupg=2.2.27-3ubuntu2.1
      state: present
      update_cache: true
  become: true

- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  become: true

- name: Add Docker Repository
  ansible.builtin.apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      state: present
  become: true

- name: Update apt and install docker-ce
  ansible.builtin.apt:
      name:
          - "docker-ce={{ docker_version }}"
          - "docker-ce-cli={{ docker_version }}"
      state: present
      allow_downgrade: true
      force: true
  become: true

- name: Install SDK docker and jsondiff (python)
  ansible.builtin.pip:
      name:
          - docker
          - jsondiff
      state: present
  become: true

- name: Check if Swarm cluster exists
  become: true
  community.docker.docker_host_info:
  register: docker_info
```

##### EXPECTED RESULTS

I expect to get docker info

##### ACTUAL RESULTS

This error happened on my 3 servers

```paste below
The full traceback is:
  File "/tmp/ansible_community.docker.docker_host_info_payload_316ufw33/ansible_community.docker.docker_host_info_payload.zip/ansible_collections/community/docker/plugins/module_utils/common_api.py", line 117, in __init__
    super(AnsibleDockerClientBase, self).__init__(**self._connect_params)
  File "/tmp/ansible_community.docker.docker_host_info_payload_316ufw33/ansible_community.docker.docker_host_info_payload.zip/ansible_collections/community/docker/plugins/module_utils/_api/api/client.py", line 188, in __init__
    self._version = self._retrieve_server_version()
  File "/tmp/ansible_community.docker.docker_host_info_payload_316ufw33/ansible_community.docker.docker_host_info_payload.zip/ansible_collections/community/docker/plugins/module_utils/_api/api/client.py", line 212, in _retrieve_server_version
    raise DockerException(
fatal: [swarm-01]: FAILED! => {
    "can_talk_to_docker": false,
    "changed": false,
    "invocation": {
        "module_args": {
            "api_version": "auto",
            "ca_cert": null,
            "client_cert": null,
            "client_key": null,
            "containers": false,
            "containers_all": false,
            "containers_filters": null,
            "debug": false,
            "disk_usage": false,
            "docker_host": "unix://var/run/docker.sock",
            "images": false,
            "images_filters": null,
            "networks": false,
            "networks_filters": null,
            "ssl_version": null,
            "timeout": 60,
            "tls": false,
            "tls_hostname": null,
            "use_ssh_client": false,
            "validate_certs": false,
            "verbose_output": false,
            "volumes": false,
            "volumes_filters": null
        }
    },
    "msg": "Error connecting: Error while fetching server API version: Not supported URL scheme http+docker"
}
```
