### ISSUE TITLE
docker_container: enable use of the "host-gateway" flag in the "etc_hosts" parameter

### ISSUE THREAD

**Issue by jefersoonaf** [ansible-collections/community.docker#888]
##### SUMMARY

Enable use of the `host-gateway` flag in the `etc_hosts` parameter, the same can be done with `docker run` and `docker compose`.

This flag helps configure communication from an application within the container to something running on the host machine without Docker needing to be configured with `--network=host`.

For example, enabling a pgadmin4 container to connect to PostgreSQL that is installed on the host machine through port 5432 and being able to define the connection host equal to `host.docker.internal`.

With `docker run`:
```bash
docker run -p 80:80 \
 -e 'PGADMIN_DEFAULT_EMAIL=admin@admin.com' \
 -e 'PGADMIN_DEFAULT_PASSWORD=admin' \
 -d dpage/pgadmin4 \
 --add-host=host.docker.internal:host-gateway
```

With `docker compose`:
```yaml
services:
 postgres:
 image: dpage/pgadmin4:latest
 environment:
 - PGADMIN_DEFAULT_EMAIL=admin@admin.com
 - PGADMIN_DEFAULT_PASSWORD=admin
 ports:
 - "80:80"
 extra_hosts:
 - "host.docker.internal:host-gateway"
```

Considering that the IP of the `docker0` network interface is equal to `172.17.0.1`, in both cases, the line below will be added to the container's /etc/hosts file:
```bash
host.docker.internal     172.17.0.1
```

References:
  - https://docs.docker.com/reference/cli/docker/container/run/?highlight=hostgateway#add-host
  - https://docs.docker.com/reference/cli/dockerd/#configure-host-gateway-ip

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

`community.docker.docker_container`

##### ADDITIONAL INFORMATION

Suggestion on how it could be implemented for the `community.docker.docker_container` module through the existing parameter `etc_hosts`:
```yaml
- name: Create pgAdmin4 container
  community.docker.docker_container:
    name: pgadmin4
    image: dpage/pgadmin4:latest
    ports:
      - "{{ pgadmin_port }}:80"
    restart: true
    restart_policy: always
    state: started
    volumes:
      - /pgadmin4/servers.json:/pgadmin4/servers.json:ro
    env:
      PGADMIN_DEFAULT_EMAIL: "{{ pgadmin_login }}"
      PGADMIN_DEFAULT_PASSWORD: "{{ pgadmin_password }}"
      # PGADMIN_ENABLE_TLS: "true"
    etc_hosts: 
      host.docker.internal: host-gateway
```

This collection is excellent and serves me very well in several projects. And that's why I believe that this implementation will add even more value to it. Thanks.
