### ISSUE TITLE
state: healthy for docker_container

### ISSUE THREAD

**Issue by LeanderFS** [ansible-collections/community.docker#890]
##### SUMMARY
Currently it's only possible to use state `absent`, `present`, `stopped` and `started` for the docker_container module. I would like to propose adding `state: healthy` to have Ansible wait until the integrated HEALTHCHECK returns healthy (when defined in the Dockerfile).

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
community.docker.docker_container

##### ADDITIONAL INFORMATION
By implementing this feature, a playbook can halt execution until the docker_container healtcheck returns healthy. This prevents additional tasks to poll for the health manually.

```yaml
- name: Create database container
  docker_container:
    name: "database"
    image: "mysql:latest"
    state: "healthy" # This will trigger Ansible to wait for the HEALTHCHECK statement to return healthy, and fail if unhealthy.
    restart: true
    detach: true
    pull: "always"
    restart_policy: always
    published_ports:
      - "{{ db_fixture_port }}:3306"
```
