### ISSUE TITLE
docker_compose_v2 docker context switch fails

### ISSUE THREAD

**Issue by crt0r** [ansible-collections/community.docker#892]
##### SUMMARY
The *cli_context* parameter of the *community.docker.docker_compose_v2* module doesn't switch the Docker context for a command it executes underneath. Instead, the following error is thrown:

```
conflicting options: either specify --host or --context, not both
```

This happens despite the *docker_host* parameter is not explicitly set.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
docker_compose_v2

##### ANSIBLE VERSION
```paste below
ansible [core 2.16.6]
  config file = /home/tchuchkanov/projects/personal-site/ansible.cfg
  configured module search path = ['/home/tchuchkanov/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.12/site-packages/ansible
  ansible collection location = /home/tchuchkanov/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.12.3 (main, Apr 17 2024, 00:00:00) [GCC 13.2.1 20240316 (Red Hat 13.2.1-7)] (/usr/bin/python3)
  jinja version = 3.1.4
  libyaml = True
```

##### COLLECTION VERSION
```paste below
# /home/tchuchkanov/.ansible/collections/ansible_collections
Collection       Version
---------------- -------
community.docker 3.11.0 

# /usr/lib/python3.12/site-packages/ansible_collections
Collection       Version
---------------- -------
community.docker 3.9.0
```

##### CONFIGURATION
```paste below
CONFIG_FILE() = /home/tchuchkanov/projects/personal-site/ansible.cfg
DEFAULT_STDOUT_CALLBACK(/home/tchuchkanov/projects/personal-site/ansible.cfg) = yaml
EDITOR(env: EDITOR) = vim
```

##### OS / ENVIRONMENT
OS: Fedora Linux 39 (Workstation Edition)
Kernel: Linux 6.8.11-200.fc39.x86_64

##### STEPS TO REPRODUCE
1. Create a separate Docker context on a target Linux machine. *rootless*, for example.
1. Create a compose file on the target machine in a *$HOME/testdir* directory.
    ```yaml
    services:
      nginx:
        image: nginx:latest
        ports: ['80:80']
        cap_drop:
        - ALL
        cap_add:
        - CHOWN
    ```
1. Create a playbook.
    ```yaml
    - name: Docker Debug
      hosts: all

      tasks:
      - name: Run NGINX
        community.docker.docker_compose_v2:
          project_src: '{{ ansible_user_dir }}/testdir'
          cli_context: rootless
    ```
1. Run the playbook.

##### EXPECTED RESULTS
The playbook execution leads to a compose project being set up for a particular Docker context.

##### ACTUAL RESULTS
Ansible throws an error. The *docker_host* parameter default value is not ignored when the *cli_context* is provided.

```paste below
<<<OUTPUT TRIMMED FOR READABILITY>>>

fatal: [default]: FAILED! => changed=false 
  cmd: /usr/bin/docker --host unix:///var/run/docker.sock --context rootless version --format '{{ json . }}'
  invocation:
    module_args:
      api_version: auto
      build: policy
      ca_path: null
      check_files_existing: true
      cli_context: rootless
      client_cert: null
      client_key: null
      definition: null
      dependencies: true
      docker_cli: null
      docker_host: unix:///var/run/docker.sock
      env_files: null
      files: null
      profiles: null
      project_name: null
      project_src: /home/vagrant/testdir
      pull: policy
      recreate: auto
      remove_images: null
      remove_orphans: false
      remove_volumes: false
      scale: null
      services: null
      state: present
      timeout: null
      tls: false
      tls_hostname: null
      validate_certs: false
      wait: false
      wait_timeout: null
  msg: 'conflicting options: either specify --host or --context, not both'
  rc: 1
  stderr: |-
    conflicting options: either specify --host or --context, not both
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
```
