### ISSUE TITLE
'dict object' has no attribute 'services' when using `docker_compose_v2`

### ISSUE THREAD

**Issue by ShaneMcC** [ansible-collections/community.docker#912]
##### SUMMARY

When using `docker_compose_v2` with `register: output` it is no longer possible (despite documentation suggesting otherwise in the [examples](https://docs.ansible.com/ansible/latest/collections/community/docker/docker_compose_v2_module.html#examples)) to test against the value of `output.services.service.container.state.running` because `services` is no longer populated in the output dict.

`output.containers` exists, but this is just a list so can not be tested against as easily because the container name is not used as a key.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

docker_compose_v2

##### ANSIBLE VERSION

```paste below
ansible [core 2.16.3]
  config file = /home/shane/.ansible.cfg
  configured module search path = ['/home/shane/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/shane/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.12.3 (main, Apr 10 2024, 05:33:47) [GCC 13.2.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /home/shane/.ansible/collections/ansible_collections
Collection       Version
---------------- -------
community.docker 3.10.4

# /usr/lib/python3/dist-packages/ansible_collections
Collection       Version
---------------- -------
community.docker 3.7.0
```

##### CONFIGURATION

```paste below
ANSIBLE_NOCOWS(/home/shane/.ansible.cfg) = True
CONFIG_FILE() = /home/shane/.ansible.cfg
```

##### OS / ENVIRONMENT

Linux

##### STEPS TO REPRODUCE

```yaml
- name: Debug
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Run container with docker-compose.
      community.docker.docker_compose_v2:
        state: present
        pull: always
        remove_orphans: true
        project_name: ansibledemo
        wait: true
        definition:
          services:
            demo:
              image: traefik/whoami:latest
              restart: always
      register: output

    - name: Check services are running
      ansible.builtin.assert:
        that:
          - "output.services.ansibledemo.ansibledemo-demo-1.state.running"

```

##### EXPECTED RESULTS

Playbook TASK `Check services are running` to run successfully without errors.

##### ACTUAL RESULTS

```paste below
TASK [Check services are running] *******************************************************
fatal: [localhost]: FAILED! => {"msg": "The conditional check 'output.services.ansibledemo.ansibledemo-demo-1.state.running' failed. The error was: error while evaluating conditional (output.services.ansibledemo.ansibledemo-demo-1.state.running): 'dict object' has no attribute 'services'. 'dict object' has no attribute 'services'"}
```
