### ISSUE TITLE
community.docker.docker_compose_v2 module fails with dynamically generated network names

### ISSUE THREAD

**Issue by n0one42** [ansible-collections/community.docker#930]
##### SUMMARY
I am using the `community.docker.docker_compose_v2` module in Ansible and encountering an issue when trying to use dynamically generated network names. The same approach works perfectly with the `community.docker.docker_container` module.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`community.docker.docker_compose_v2`

##### ANSIBLE VERSION
```txt
ansible [core 2.17.1]
  config file = xxx/ansible.cfg
  configured module search path = ['/Users/xxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible/10.1.0/libexec/lib/python3.12/site-packages/ansible
  ansible collection location = /Users/xxx/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.12.4 (main, Jun  6 2024, 18:26:44) [Clang 15.0.0 (clang-1500.3.9.4)] (/opt/homebrew/Cellar/ansible/10.1.0/libexec/bin/python)
  jinja version = 3.1.4
  libyaml = True
```

## Playbooks
This worked
```yaml
        - name: Manage service for "{{ container_name }}"
          community.docker.docker_container:
          ...
            networks:
              - name: "{{ docker_external_net_name }}"
                ipv4_address: "{{ t2_external_net_ip }}"
              - name: "{{ t2_internal_net_name }}"
                ipv4_address: "{{ t2_internal_ip }}"
              - name: socketproxy_{{ container_name }}_net
          ...
```
Now I want to achieve the same with `community.docker.docker_compose_v2` inline like this:
```yaml
        - name: Install docker compose traefik with inline definition
          community.docker.docker_compose_v2:
            project_name: "{{ traefik_container_name }}"
            definition:
              # ! --------------------------- Networks --------------------------- ! #
              networks:
                t3_proxy_net:
                  name: "{{ traefik_net_name }}"
                  driver: bridge
                  internal: true
                  ipam:
                    config:
                      - subnet: "{{ traefik_net_cidr }}"

              # * ---------------------------- App ------------------------------ * #
              services:
                traefik:
                  container_name: "{{ traefik_container_name }}-socketproxy"  # eg: traefik-socketproxy
                  image: traefik:3.0
                  ...
                  networks:
                    - name: "{{ traefik_net_name }}"
                      ipv4_address: "{{ traefik_net_ip }}"
                    - name: "{{ traefik_container_name }}_{{ traefik_socketproxy_net_name }}"
                      ipv4_address: "{{ traefik_socketproxy_net_ip }}"
                  ...            
```

### Problem:
When defining networks dynamically in community.docker.docker_compose_v2, I receive the following error:
```terminal
"msg": "General error: validating /tmp/ansible67iv8v6z/compose.yaml: services.traefik.networks.0 must be a string"
```

### Expected behavior:
The module should accept dynamically generated network names and create the networks as specified in the playbook.

**Comment by n0one42** [comment]
I found a working solution. I had to declare the networks this way:

```yml
              networks:
                socketproxy_net:
                  name: "{{ traefik_container_name }}_{{ traefik_socketproxy_net_name }}"  # eg: traefik_socketproxy_net
                  external: true  # indicating that it's a pre-existing network not managed by this Docker Compose file.

                traefik_net:
                  name: "{{ traefik_net_name }}"
                  driver: bridge
                  internal: true
                  ipam:
                    config:
                      - subnet: "{{ traefik_net_cidr }}" # - subnet: 192.168.90.0/24
```
