### ISSUE TITLE
community.docker.docker add environment var overwrite

### ISSUE THREAD

**Issue by agowa** [ansible-collections/community.docker#937]
##### SUMMARY
Please add an option to specify environment variables. Sadly lthel existing `ansible_docker_extra_args` cannot be used to pass the `--env` option therefore a new additional option would be required.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
community.docker.docker
community.docker.docker_api

##### ADDITIONAL INFORMATION

```yaml
- name: GitLab | Add container to inventory
  ansible.builtin.add_host:
    host: '{{ gitlab_container_name }}'
    ansible_connection: docker
    ansible_docker_extra_args: '-H {{ gitlab_dockerhost }}'
    ansible_docker_extra_env:
      PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
    ansible_python_interpreter: '/usr/bin/python3'
    ansible_shell_executable: '/bin/bash'
    ansible_become: false
```
