### ISSUE TITLE
Ansible Automation Platform docker command not found in PATH when running job in an execution environment

### ISSUE THREAD

**Issue by randy-randerson** [ansible-collections/community.docker#945]
##### SUMMARY
When running a playbook through a job template on Ansible Automation Platform (AAP) running on a custom execution environment (EE), we have a task that has the remote host delegate a task to a container running on the host and the task fails with the error:

```
TASK [otf-tests : Disable connectivity to the portal] ****************
task path: /runner/project/otf/roles/otf-tests/tasks/test_offline_content_bundles.yml:29
redirecting (type: connection) ansible.builtin.docker to community.docker.docker
fatal: [otf-10108672746.bah -> sensor]: FAILED! => {
    "msg": "docker command not found in PATH"
}
```

This task worked previously on Ansible Tower 3.8.x before upgrading to AAP 2.4. We have confirmed with Red Hat support that they were able to reproduce the issue on their end and they recommended we raise an issue with the collection maintainer.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`community.docker.docker`

##### ANSIBLE VERSION

```paste below
ansible [core 2.16.7]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.11/site-packages/ansible
  ansible collection location = /runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.11.7 (main, May 16 2024, 00:00:00) [GCC 11.4.1 20231218 (Red Hat 11.4.1-3)] (/usr/bin/python3.11)
  jinja version = 3.1.4
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /usr/share/ansible/collections/ansible_collections
Collection       Version
---------------- -------
community.docker 3.10.1

```
We've also tried on the latest release 3.11.0 and got the same error

##### CONFIGURATION

```paste below
bash-5.1$ ansible-config dump --only-changed
CONFIG_FILE() = /etc/ansible/ansible.cfg
```

##### OS / ENVIRONMENT

runner/custom EE OS:
```
NAME="Red Hat Enterprise Linux"
VERSION="9.4 (Plow)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="9.4"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Red Hat Enterprise Linux 9.4 (Plow)"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:redhat:enterprise_linux:9::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_BUGZILLA_PRODUCT_VERSION=9.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.4"
```

Host system:
```
NAME=""
VERSION="5.3.1"
ID="ol"
ID_LIKE="fedora"
VARIANT=""
VARIANT_ID=""
VERSION_ID="8.5"
PLATFORM_ID="platform:el8"
PRETTY_NAME=""
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:8:5:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 8"
ORACLE_BUGZILLA_PRODUCT_VERSION=8.5
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=8.5
```

##### STEPS TO REPRODUCE

This task runs shell commands on a container from the host system using the ansible_connection: docker setup

```yaml
This is the task that fails:

- name: Disable connectivity to the portal
  delegate_to: sensor
  vars:
    ansible_user: root
  shell: |
    bv-cfg <<EOF
    set system.management.data.updates.portal.updates_url ''
    stage
    deploy
    EOF
  register: stdout
  changed_when: false

Here is the task that sets up the docker connection:

---
- name: Add containers to host inventory
  add_host:
    name: "{{ item }}"
    ansible_connection: docker
    ansible_docker_extra_args: "-H=tcp://{{ ansible_host }}"
  with_items:
    - ingest
    - sensor
    - hostinfo
    - bv-gui
    - bv-gui-celery
    - bv-intel
    - artifact-storage
    - artifact-storage-celery
    - cockpit
  changed_when: false
```

##### EXPECTED RESULTS

The AAP job template should run, connect to the host system and then delegate the task to the container to run some shell commands.

##### ACTUAL RESULTS

The task fails with the below error

```paste below
TASK [otf-tests : Disable connectivity to the portal] ****************
task path: /runner/project/otf/roles/otf-tests/tasks/test_offline_content_bundles.yml:29
redirecting (type: connection) ansible.builtin.docker to community.docker.docker
fatal: [otf-10108672746.bah -> sensor]: FAILED! => {
    "msg": "docker command not found in PATH"
}
```
