### ISSUE TITLE
Implement entrypoint for docker_swarm_service

### ISSUE THREAD

**Issue by pedroterzero** [ansible-collections/community.docker#955]
##### SUMMARY

It would be good to be able to define the [entrypoint for the service](https://docs.docker.com/reference/cli/docker/service/create/). Unless there's a reason why it shouldn't be possible, but then perhaps it would be good to document it. 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

docker_swarm_service

##### ADDITIONAL INFORMATION

Allow to configure entrypoint for a service.

```yaml
      community.docker.docker_swarm_service:
        image: "mongo:7.0"
        entrypoint: "docker-entrypoint.sh"
        # ...
```
