### ISSUE TITLE
Use docker prune command to remove by missing label

### ISSUE THREAD

**Issue by Jimmy-Newtron** [ansible-collections/community.docker#961]
I don't get how to remove every container that does not have a specific label

https://docs.docker.com/reference/cli/docker/container/prune/#filter

As per docker filter documentation we have the possibility to use a negative filter syntax `label!=<key>=<value>`

How can it be done?

**Comment by felixfontein** [comment]
The CLI seems to treat `label!=...` the same as `label=...`, so maybe try:
```yaml
  containers_filters:
    "label!": "<key>=<value>"
```
Or if you have multiple labels that should not match:
```yaml
  containers_filters:
    "label!":
      - "<key>=<value>"
      - "<key2>=<value2>"
```
Does that work? If yes, I think we should add examples for that to the docs.

**Comment by erlingtonjcardoza** [comment]
@felixfontein not working.

I'm testing with this:

```
- name: Get current container info
  community.docker.docker_container_info:
    name: mongodb
  register: current_container_info

- name: Prune unused MongoDB images
  community.docker.docker_prune:
    images: yes
    images_filters:
      "label!": 
        - "org.opencontainers.image.version={{ current_container_info.container.Config.Labels['org.opencontainers.image.version'] }}"
```
Despite having orphaned images, when the task runs, no images are listed.

**Comment by felixfontein** [comment]
It turns out that there's a bug in the module. If you provide a list, mulitated. If you provide a single string value, it works fine. I've created #966 to fix this.

For a single label, simply use the non-list form, that should work already now:
```yaml
- name: Get current container info
  community.docker.docker_container_info:
    name: mongodb
  register: current_container_info

- name: Prune unused MongoDB images
  community.docker.docker_prune:
    images: yes
    images_filters:
      "label!": "org.opencontainers.image.version={{ current_container_info.container.Config.Labels['org.opencontainers.image.version'] }}"
```
