### ISSUE TITLE
[WARNING]: Cannot parse event from line: 'container foo exited (0)

### ISSUE THREAD

**Issue by grzs** [ansible-collections/community.docker#978]
##### SUMMARY
module community.docker.docker_compose_v2 fails to start project because of parse error

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
docker_compose_v2

##### ANSIBLE VERSION
```
ansible [core 2.17.4]
  config file = None
  configured module search path = ['/home/jgerzson/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jgerzson/.virtualenvs/ansible/lib/python3.10/site-packages/ansible
  ansible collection location = /home/jgerzson/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/jgerzson/.virtualenvs/ansible/bin/ansible
  python version = 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0] (/home/jgerzson/.virtualenvs/ansible/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION
```
Collection       Version
---------------- -------
community.docker 3.12.1 
```

##### CONFIGURATION
```
CONFIG_FILE() = None
EDITOR(env: EDITOR) = vim
PAGER(env: PAGER) = less
```

##### OS / ENVIRONMENT
target OS: Alpine Linux in Docker container

##### STEPS TO REPRODUCE
```yaml
- name: ensure compose project is initialized
  community.docker.docker_compose_v2:
    project_src: "{{ compose_project_dir }}"
    wait: true
```

##### EXPECTED RESULTS
no error

##### ACTUAL RESULTS
```
TASK [postgres : debug] ********************************************************                                                                                      
ok: [molecule_instance1] => {                                                                                                                                         
    "init": {                                                                                                                                                                 "actions": [                                                                                                                                                  
            {                                                                                                                                                         
                "id": "create_users_db_default",                                   
                "status": "Creating",                                              
                "what": "network"        
            },                                                                     
            {                                                                      
                "id": "create_users_db-init",                                      
                "status": "Creating",                                              
                "what": "container"                                                                                                                                   
            },                                                                     
            {                                                                      
                "id": "create_users_db-init",                                      
                "status": "Starting",                                              
                "what": "container"                                                
            }                            
        ],                                                                         
        "changed": true,                                                                                                                                              
        "cmd": "/usr/local/bin/docker compose --ansi never --progress plain --project-directory /opt/postgres/create_users_db up --detach --no-color --quiet-pull --wa
it postgres-init --",                                                              
        "containers": [                                                            
            {                            
                "Command": "\"/client-entrypoint.sh init_volumes\"",                                                                                                  
                "CreatedAt": "2024-10-19 12:44:06 +0000 UTC",                                                                                                         
                "ExitCode": 0,                                                                                                                                        
                "Health": "",                                                                                                                                         
                "ID": "556a5741f3681008905fe22b6ea7810a60a574d043123d640252becd0affc867",                                                                             
                "Image": "docker.io/foo/postgres-client:latest",             
                "Labels": {},
                "LocalVolumes": "2",
                "Mounts": "/opt/postgres/create_users_db/.dummy,create_users_db_db-init,create_users_db_db-preinit,/opt/postgres/create_users_db/backup/db,/opt/postgr
es/create_users_db/logs",
                "Name": "create_users_db-init",
                "Names": [
                    "create_users_db-init"
                ],
                "Networks": [
                    "create_users_db_default"
                ],
                "Ports": "",
                "Project": "create_users_db",
                "Publishers": [],
                "RunningFor": "Less than a second ago",
                "Service": "postgres-init",
                "Size": "0B",
                "State": "exited",
                "Status": "Exited (0) Less than a second ago"
            }
        ],
        "failed": false,
        "failed_when_result": false,
        "images": [
            {
                "ContainerName": "create_users_db-init",
                "ID": "sha256:6b047307059b20e26f8523dcb7e6b68221bb583e5d4194b3612962c21eb5affc",
                "Repository": "foo/postgres-client",
                "Size": 279185327,
                "Tag": "latest"
            }
        ],
        "msg": "Return code 1 is non-zero",
        "rc": 1,
        "stderr": " Network create_users_db_default  Creating\n Network create_users_db_default  Created\n Container create_users_db-init  Creating\n Container create
_users_db-init  Created\n Container create_users_db-init  Starting\n Container create_users_db-init  Started\n Container create_users_db-init  Waiting\ncontainer crea
te_users_db-init exited (0)\n",
        "stderr_lines": [
            " Network create_users_db_default  Creating",
            " Network create_users_db_default  Created",
            " Container create_users_db-init  Creating",
            " Container create_users_db-init  Created",
            " Container create_users_db-init  Starting",
            " Container create_users_db-init  Started",
            " Container create_users_db-init  Waiting",
            "container create_users_db-init exited (0)"
        ],
        "stdout": "",
        "stdout_lines": [],
        "warnings": [
            "Cannot parse event from line: 'container create_users_db-init exited (0)'. Please report this at https://github.com/ansible-collections/community.docker/
issues/new?assignees=&labels=&projects=&template=bug_report.md"
        ]
    }
}
```

**Comment by grzs** [comment]
@felixfontein thank you for the quick response.
The task starts one service which purposefully exits after completing its job (init container).
Is it possible to compose itself returns non-zero code when everything goes well?
I run the docker command from the terminal and examine the output.

**Comment by grzs** [comment]
as a workaround I run it with a failed_when check for the last line of stderr_lines

**Comment by felixfontein** [comment]
> The task starts one service which purposefully exits after completing its job (init container).

You told the module to wait for the container to be up/healthy (`wait: true`). That's why Docker Compose fails, since the container exits before it becomes healthy.

The line `container create_users_db-init exited (0)` is in fact the error message returned by Docker Compose. (Older verisons of Docker Compose do not allow to return JSON stream stderr output; with newer versions this is more obvious, you'd get `{"error":true,"message":"container create_users_db-init exited (0)"}` instead.)

Right now the module does not support starting services without `--detach`, which is probably what you want to use. It would help if you could write which command you would run on the command line to achieve what you want.

**Comment by grzs** [comment]
Originally I ran the whole project without specifying the service, because it has depends_on directives to make the main container wait for the init container to finish, but when I ran it via the module without the wait option, it didn't. respect the depends_on rules, and couldn't; start properly. Here is the corresponding compose fragment:

'''yaml
services:
  postgres-main:
    image: ${POSTGRESQL_REGISTRY_URL}/postgres-server:${POSTGRESQL_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}-main
    depends_on:
      postgres-init:
        condition: service_completed_successfully
'''

**Comment by felixfontein** [comment]
I was asking for the `docker compose ...` command line you would be using.

**Comment by grzs** [comment]
basically 'docker compose up -d' used to work as expected

**Comment by grzs** [comment]
exactly, I can reproduce the error like this:
-  delete (down) the project and its volumes
- run 'docker compose up -d' form the command line - works
- deleting the containers and volumes again
- run via ansible - fails

**Comment by grzs** [comment]
it seems that the module doesn't respect the depends_on: service_completed_successfully directive

**Comment by felixfontein** [comment]
The module simply calls `docker compose ...` with the exact command line it provides you in the error message. It doesn't every try to parse the service definition.

**Comment by grzs** [comment]
![image](https://github.com/user-attachments/assets/a988e67e-247a-49c7-b463-469bd33082fd)

**Comment by grzs** [comment]
maybe it's related to docker compose running in python subprocess (I suppose)

**Comment by felixfontein** [comment]
You might want to write what exactly you are running on the Ansible side and what the output is, because what you wrote in the issue does not match the command you are running now (there's `wait: true`).

**Comment by grzs** [comment]
![image](https://github.com/user-attachments/assets/448e0052-110d-4718-9742-1e1b2804d8ec)

**Comment by grzs** [comment]
without --wait the exit code is 0

**Comment by grzs** [comment]
originally I tried to do only this in the role handlers main.yml:

```yaml
- name: ensure postgres project is down
  listen:
    - postgres_stop
    - postgres_restart
  community.docker.docker_compose_v2:
    project_src: "{{ postgres_project_dir }}"
    state: absent
  when:
    - postgres_project_state != 'absent'

- name: ensure postgres project is {{ postgres_project_state }}
  listen:
    - postgres_restart
    - postgres_set_state
  community.docker.docker_compose_v2:
    project_src: "{{ postgres_project_dir }}"
    state: "{{ postgres_project_state }}"
```

**Comment by grzs** [comment]
and here is the workaround in the end of tasks/main.yml:

```yaml
- name: ensure .init marker file is there
  ansible.builtin.copy:
    dest: "{{ postgres_project_dir }}/.init"
    content: ""
  register: init_file
- name: ensure compose project is initialized
  community.docker.docker_compose_v2:
    project_src: "{{ postgres_project_dir }}"
    wait: true
    services:
      - postgres-init
  when: init_file is changed
  register: init
  failed_when: not init.stderr_lines | last | regex_search('^container [a-z0-9_-]+ exited \(0\)$')
```

**Comment by felixfontein** [comment]
```yaml
  community.docker.docker_compose_v2:
    project_src: "{{ postgres_project_dir }}"
    state: "{{ postgres_project_state }}"
```
should do pretty much the same as calling `docker compose up --detach`. So what is the output you are getting there?
