### ISSUE TITLE
Add check mode support for `docker_compose_v2_exec`

### ISSUE THREAD

**Issue by Apollo-Roboto** [ansible-collections/community.docker#983]
##### SUMMARY

Ability to use `check_mode: true` with `docker_compose_v2_exec`, similar to the builtin command

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

community.docker.docker_compose_v2_exec

##### ADDITIONAL INFORMATION

Similarly to the builtin commands, there could be cases where you need to call a non destructive command to check if another task is needed.

```yaml
- name: Check if folder exists inside the container
  community.docker.docker_compose_v2_exec:
    service: "myservice"
    command: "test -e /app/special_folder"
    project_src: "/path/to/compose.yaml"
  register: folder_test
  failed_when: folder_test.rc > 1
  changed_when: false
  check_mode: true     # <-- HERE!

- name: Action if folder exists
  community.docker.docker_compose_v2_exec:
    service: "myservice"
    command: "touch /app/special_folder/thing.txt"
    project_src: "/path/to/compose.yaml"
  when: folder_test.rc == 0

```
